<?php

use App\Http\Controllers\Api\V1\AdminAuthController;
use App\Http\Controllers\Api\V1\Admin\AdminBootstrapController;
use App\Http\Controllers\Api\V1\Admin\AdminConfigurationController;
use App\Http\Controllers\Api\V1\Admin\AdminDashboardController;
use App\Http\Controllers\Api\V1\Admin\AdminRatingReviewsController;
use App\Http\Controllers\Api\V1\Admin\AdminAffiliateCommissionController;
use App\Http\Controllers\Api\V1\Admin\AdminBlogContributionsController;
use App\Http\Controllers\Api\V1\Admin\AdminBlogCommentsController;
use App\Http\Controllers\Api\V1\Admin\AdminBlogPostsController;
use App\Http\Controllers\Api\V1\Admin\AdminBlogPostCategoriesController;
use App\Http\Controllers\Api\V1\Admin\AdminCategoriesController;
use App\Http\Controllers\Api\V1\Admin\AdminContentBlocksController;
use App\Http\Controllers\Api\V1\Admin\AdminContentPagesController;
use App\Http\Controllers\Api\V1\Admin\AdminCountriesController;
use App\Http\Controllers\Api\V1\Admin\AdminCourseLanguagesController;
use App\Http\Controllers\Api\V1\Admin\AdminCourseEditRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminCourseRefundRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminCourseRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminCoursesController;
use App\Http\Controllers\Api\V1\Admin\AdminGroupClassesController;
use App\Http\Controllers\Api\V1\Admin\AdminLessonStatsController;
use App\Http\Controllers\Api\V1\Admin\AdminSalesReportController;
use App\Http\Controllers\Api\V1\Admin\AdminSitemapController;
use App\Http\Controllers\Api\V1\Admin\AdminMetaTagsController;
use App\Http\Controllers\Api\V1\Admin\AdminUrlRewritingController;
use App\Http\Controllers\Api\V1\Admin\AdminBotsController;
use App\Http\Controllers\Api\V1\Admin\AdminModuleController;
use App\Http\Controllers\Api\V1\Admin\AdminPreferencesController;
use App\Http\Controllers\Api\V1\Admin\AdminSpeakLanguageLevelsController;
use App\Http\Controllers\Api\V1\Admin\AdminForumQuestionsController;
use App\Http\Controllers\Api\V1\Admin\AdminForumReportedQuestionsController;
use App\Http\Controllers\Api\V1\Admin\AdminForumReportReasonsController;
use App\Http\Controllers\Api\V1\Admin\AdminForumTagRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminForumTagsController;
use App\Http\Controllers\Api\V1\Admin\AdminGdprRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminIssueReportOptionsController;
use App\Http\Controllers\Api\V1\Admin\AdminSpeakLanguagesController;
use App\Http\Controllers\Api\V1\Admin\AdminTeachLanguagesController;
use App\Http\Controllers\Api\V1\Admin\AdminQuestionsController;
use App\Http\Controllers\Api\V1\Admin\AdminCommissionController;
use App\Http\Controllers\Api\V1\Admin\AdminCouponsController;
use App\Http\Controllers\Api\V1\Admin\AdminSocialPlatformController;
use App\Http\Controllers\Api\V1\Admin\AdminSlidesController;
use App\Http\Controllers\Api\V1\Admin\AdminStatesController;
use App\Http\Controllers\Api\V1\Admin\AdminPaymentMethodsController;
use App\Http\Controllers\Api\V1\Admin\AdminMeetingToolsController;
use App\Http\Controllers\Api\V1\Admin\AdminCurrencyController;
use App\Http\Controllers\Api\V1\Admin\AdminNavigationsController;
use App\Http\Controllers\Api\V1\Admin\AdminPageLangDataController;
use App\Http\Controllers\Api\V1\Admin\AdminThemesController;
use App\Http\Controllers\Api\V1\Admin\AdminPageTextController;
use App\Http\Controllers\Api\V1\Admin\AdminOrdersController;
use App\Http\Controllers\Api\V1\Admin\AdminQuizzesController;
use App\Http\Controllers\Api\V1\Admin\AdminTeacherRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminWithdrawRequestsController;
use App\Http\Controllers\Api\V1\Admin\AdminAdminPermissionsController;
use App\Http\Controllers\Api\V1\Admin\AdminManageAdminsController;
use App\Http\Controllers\Api\V1\Admin\AdminUsersController;
use App\Http\Controllers\Api\V1\Admin\AdminVideoContentController;
use App\Http\Controllers\Api\V1\Admin\AdminTestimonialsController;
use App\Http\Controllers\Api\V1\Admin\AdminLanguageLabelsController;
use App\Http\Controllers\Api\V1\Admin\AdminFaqCategoriesController;
use App\Http\Controllers\Api\V1\Admin\AdminFaqController;
use App\Http\Controllers\Api\V1\Admin\AdminEmailTemplatesController;
use App\Http\Controllers\Api\V1\Admin\AdminAbusiveWordsController;
use App\Http\Controllers\Api\V1\Admin\AdminCertificatesController;
use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\ChatController;
use App\Http\Controllers\Api\V1\BlogController;
use App\Http\Controllers\Api\V1\ContentController;
use App\Http\Controllers\Api\V1\CookieConsentController;
use App\Http\Controllers\Api\V1\CourseController;
use App\Http\Controllers\Api\V1\FaqController;
use App\Http\Controllers\Api\V1\ForumController;
use App\Http\Controllers\Api\V1\GroupClassController;
use App\Http\Controllers\Api\V1\HomeController;
use App\Http\Controllers\Api\V1\ImageController;
use App\Http\Controllers\Api\V1\LectureController;
use App\Http\Controllers\Api\V1\LessonController;
use App\Http\Controllers\Api\V1\MyCourseController;
use App\Http\Controllers\Api\V1\SearchController;
use App\Http\Controllers\Api\V1\SiteController;
use App\Http\Controllers\Api\V1\TeacherController;
use App\Http\Controllers\Api\V1\DashboardForumController;
use App\Http\Controllers\Api\V1\DashboardForumSubscribedTagsController;
use App\Http\Controllers\Api\V1\DashboardGiftcardsController;
use App\Http\Controllers\Api\V1\DashboardCoursesController;
use App\Http\Controllers\Api\V1\DashboardTeacherCoursesController;
use App\Http\Controllers\Api\V1\DashboardAttachQuizzesController;
use App\Http\Controllers\Api\V1\DashboardPlansController;
use App\Http\Controllers\Api\V1\DashboardPagesController;
use App\Http\Controllers\Api\V1\DashboardQuestionsController;
use App\Http\Controllers\Api\V1\DashboardQuizQuestionsController;
use App\Http\Controllers\Api\V1\DashboardQuizzesController;
use App\Http\Controllers\Api\V1\DashboardOrdersController;
use App\Http\Controllers\Api\V1\DashboardStudentsController;
use App\Http\Controllers\Api\V1\DashboardTeachersController;
use App\Http\Controllers\Api\V1\DashboardWalletController;
use App\Http\Controllers\Api\V1\DashboardWithdrawalsController;
use App\Http\Controllers\Api\V1\LearnerDashboardController;
use App\Http\Controllers\Api\V1\TeacherDashboardController;
use App\Http\Controllers\Api\V1\TeacherAccountController;
use App\Http\Controllers\Api\V1\TeacherAddressController;
use App\Http\Controllers\Api\V1\TeacherAvailabilityCalendarController;
use App\Http\Controllers\Api\V1\UserController;
use App\Http\Controllers\Api\V1\UserProfileController;
use App\Http\Controllers\Api\V1\VideoContentController;
use App\Http\Controllers\Api\V1\UserAccountSecurityController;
use App\Http\Controllers\Api\V1\UserGdprController;
use App\Http\Controllers\Api\V1\UserPaymentController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::get('health', fn () => response()->json(['status' => 'ok']));

    Route::get('site/bootstrap', [SiteController::class, 'bootstrap']);
    Route::get('search/autocomplete', [SearchController::class, 'autocomplete']);
    Route::get('home', [HomeController::class, 'index']);
    Route::get('image/show/{fileType}/{recordId}/{size?}/{langId?}', [ImageController::class, 'show'])
        ->where(['fileType' => '[0-9]+', 'recordId' => '[0-9]+', 'langId' => '[0-9]*']);
    Route::get('image/show-by-id/{fileId}/{size?}', [ImageController::class, 'showById'])
        ->where('fileId', '[0-9]+');
    Route::get('flags/{code}', [ImageController::class, 'flag'])
        ->where('code', '[A-Za-z0-9]{2,3}');

    Route::post('auth/login', [AuthController::class, 'login']);
    Route::post('auth/register', [AuthController::class, 'register']);
    Route::post('auth/affiliate-register', [AuthController::class, 'affiliateRegister']);
    Route::post('auth/forgot-password', [AuthController::class, 'forgotPassword']);
    Route::get('auth/reset-password/{userId}/{token}', [AuthController::class, 'validateResetPassword'])
        ->where(['userId' => '[0-9]+', 'token' => '.+']);
    Route::post('auth/reset-password', [AuthController::class, 'resetPassword']);
    Route::post('admin/auth/login', [AdminAuthController::class, 'login']);

    Route::get('courses/filters', [CourseController::class, 'filters']);
    Route::get('courses', [CourseController::class, 'index']);
    Route::get('courses/slug/{slug}', [CourseController::class, 'showBySlug']);
    Route::get('courses/{course}', [CourseController::class, 'show']);
    Route::get('courses/{course}/curriculum', [CourseController::class, 'curriculum']);
    Route::get('courses/{course}/intended-learners', [CourseController::class, 'intendedLearners']);
    Route::get('courses/{course}/reviews', [CourseController::class, 'reviews']);
    Route::get('courses/{course}/lectures/{lecture}', [LectureController::class, 'show']);

    Route::get('faq', [FaqController::class, 'index']);
    Route::get('sitemap/html', [\App\Http\Controllers\Api\V1\SitemapController::class, 'html']);
    Route::get('forum/meta', [ForumController::class, 'meta']);
    Route::get('forum/questions', [ForumController::class, 'questions']);
    Route::get('forum/questions/{slug}', [ForumController::class, 'show']);
    Route::get('blog', [BlogController::class, 'index']);
    Route::get('videos', [VideoContentController::class, 'index']);
    Route::get('blog/{post}', [BlogController::class, 'show'])->where('post', '[0-9]+');
    Route::post('blog/{post}/comments', [BlogController::class, 'storeComment'])
        ->where('post', '[0-9]+')
        ->middleware('auth:sanctum');
    Route::get('group-classes', [GroupClassController::class, 'index']);
    Route::get('group-classes/{slug}', [GroupClassController::class, 'show']);
    Route::get('content/contact', [ContentController::class, 'contact']);
    Route::post('content/contact', [ContentController::class, 'contactSubmit']);
    Route::get('content/apply-to-teach', [ContentController::class, 'applyToTeach']);
    Route::get('content/affiliate-signup', [ContentController::class, 'affiliateSignup']);
    Route::get('content/cms/{identifier}', [ContentController::class, 'cms']);

    Route::get('teachers', [TeacherController::class, 'index']);
    Route::get('teachers/{teacher}', [TeacherController::class, 'show']);
    Route::get('teachers/{teacher}/availability', [TeacherController::class, 'availabilityMeta']);
    Route::get('teachers/{teacher}/availability/slots', [TeacherController::class, 'availabilitySlots']);

    Route::middleware('auth:sanctum')->group(function () {
        Route::get('teachers/{teacher}/booking-options', [TeacherController::class, 'bookingOptions']);
        Route::post('chats/private-thread', [ChatController::class, 'privateThread']);
        Route::post('auth/logout', [AuthController::class, 'logout']);
        Route::get('auth/me', [AuthController::class, 'me']);
        Route::get('users/me', [UserController::class, 'me']);
        Route::patch('users/me', [UserController::class, 'update']);
        Route::get('users/me/profile/general', [UserProfileController::class, 'showGeneral']);
        Route::put('users/me/profile/general', [UserProfileController::class, 'updateGeneral']);
        Route::get('users/me/profile/languages/{langId}', [UserProfileController::class, 'showLanguage']);
        Route::put('users/me/profile/languages/{langId}', [UserProfileController::class, 'updateLanguage']);
        Route::get('users/me/profile/photos', [UserProfileController::class, 'showPhotos']);
        Route::post('users/me/profile/photos', [UserProfileController::class, 'uploadPhoto']);
        Route::delete('users/me/profile/photos', [UserProfileController::class, 'removePhoto']);
        Route::put('users/me/profile/photos', [UserProfileController::class, 'updatePhotos']);
        Route::put('users/me/password', [UserAccountSecurityController::class, 'changePassword']);
        Route::put('users/me/email', [UserAccountSecurityController::class, 'changeEmail']);
        Route::get('users/me/cookie-consent', [CookieConsentController::class, 'show']);
        Route::put('users/me/cookie-consent', [CookieConsentController::class, 'update']);
        Route::post('users/me/cookie-consent/accept-all', [CookieConsentController::class, 'acceptAll']);
        Route::get('users/me/delete-account', [UserGdprController::class, 'show']);
        Route::post('users/me/delete-account', [UserGdprController::class, 'store']);
        Route::get('users/me/payments', [UserPaymentController::class, 'index']);
        Route::put('users/me/payments/bank', [UserPaymentController::class, 'updateBank']);
        Route::put('users/me/payments/paypal', [UserPaymentController::class, 'updatePaypal']);
        Route::get('lessons', [LessonController::class, 'index']);
        Route::get('lessons/{lesson}', [LessonController::class, 'show']);
        Route::get('teacher/dashboard', [TeacherDashboardController::class, 'index']);
        Route::get('teacher/dashboard/scheduled-sessions', [TeacherDashboardController::class, 'scheduledSessions']);
        Route::get('account/teacher', [TeacherAccountController::class, 'show']);
        Route::get('account/teacher/progress', [TeacherAccountController::class, 'progress']);
        Route::put('account/teacher/languages', [TeacherAccountController::class, 'updateLanguages']);
        Route::put('account/teacher/prices', [TeacherAccountController::class, 'updatePrices']);
        Route::put('account/teacher/preferences', [TeacherAccountController::class, 'updatePreferences']);
        Route::post('account/teacher/qualifications', [TeacherAccountController::class, 'storeQualification']);
        Route::put('account/teacher/qualifications/{qualification}', [TeacherAccountController::class, 'updateQualification']);
        Route::delete('account/teacher/qualifications/{qualification}', [TeacherAccountController::class, 'deleteQualification']);
        Route::get('account/teacher/addresses', [TeacherAddressController::class, 'index']);
        Route::get('account/teacher/addresses/{address}', [TeacherAddressController::class, 'show']);
        Route::post('account/teacher/addresses', [TeacherAddressController::class, 'store']);
        Route::put('account/teacher/addresses/{address}', [TeacherAddressController::class, 'update']);
        Route::delete('account/teacher/addresses/{address}', [TeacherAddressController::class, 'destroy']);
        Route::get('account/teacher/availability/context', [TeacherAvailabilityCalendarController::class, 'context']);
        Route::get('account/teacher/availability/general', [TeacherAvailabilityCalendarController::class, 'generalEvents']);
        Route::get('account/teacher/availability/weekly', [TeacherAvailabilityCalendarController::class, 'weeklyEvents']);
        Route::put('account/teacher/availability/general', [TeacherAvailabilityCalendarController::class, 'saveGeneral']);
        Route::put('account/teacher/availability/weekly', [TeacherAvailabilityCalendarController::class, 'saveWeekly']);
        Route::get('account/teacher/availability/progress', [TeacherAvailabilityCalendarController::class, 'progress']);
        Route::get('learner/dashboard', [LearnerDashboardController::class, 'index']);
        Route::get('dashboard/students', [DashboardStudentsController::class, 'index']);
        Route::get('dashboard/students/{learnerId}/offer', [DashboardStudentsController::class, 'offerForm'])->whereNumber('learnerId');
        Route::put('dashboard/students/{learnerId}/offer', [DashboardStudentsController::class, 'updateOffer'])->whereNumber('learnerId');
        Route::get('dashboard/teachers', [DashboardTeachersController::class, 'index']);
        Route::get('dashboard/wallet', [DashboardWalletController::class, 'index']);
        Route::get('dashboard/orders', [DashboardOrdersController::class, 'index']);
        Route::get('dashboard/courses', [DashboardCoursesController::class, 'index']);
        Route::get('dashboard/courses/filters', [DashboardCoursesController::class, 'filters']);
        Route::get('dashboard/teacher/courses/filters', [DashboardTeacherCoursesController::class, 'courseFilters']);
        Route::get('dashboard/teacher/courses/search', [DashboardTeacherCoursesController::class, 'searchCourses']);
        Route::get('dashboard/teacher/resources/search', [DashboardTeacherCoursesController::class, 'searchResources']);
        Route::get('dashboard/teacher/course-edit-requests/filters', [DashboardTeacherCoursesController::class, 'editRequestFilters']);
        Route::get('dashboard/teacher/course-edit-requests/search', [DashboardTeacherCoursesController::class, 'searchEditRequests']);
        Route::get('dashboard/notifications', [DashboardPagesController::class, 'notifications']);
        Route::get('dashboard/plans', [DashboardPagesController::class, 'plans']);
        Route::get('dashboard/plans/{planId}', [DashboardPlansController::class, 'show'])->whereNumber('planId');
        Route::post('dashboard/plans', [DashboardPlansController::class, 'store']);
        Route::delete('dashboard/plans/{planId}', [DashboardPlansController::class, 'destroy'])->whereNumber('planId');
        Route::delete('dashboard/plans/{planId}/files/{fileId}', [DashboardPlansController::class, 'destroyFile'])
            ->whereNumber(['planId', 'fileId']);
        Route::get('dashboard/classes', [DashboardPagesController::class, 'classes']);
        Route::get('dashboard/packages', [DashboardPagesController::class, 'packages']);
        Route::get('dashboard/issues', [DashboardPagesController::class, 'issues']);
        Route::get('dashboard/subscriptions', [DashboardPagesController::class, 'subscriptions']);
        Route::get('dashboard/subscription-plans', [DashboardPagesController::class, 'subscriptionPlans']);
        Route::get('dashboard/chats', [DashboardPagesController::class, 'chats']);
        Route::get('dashboard/withdrawals', [DashboardWithdrawalsController::class, 'index']);
        Route::get('dashboard/resources', [DashboardPagesController::class, 'resources']);
        Route::get('dashboard/course-edit-requests', [DashboardPagesController::class, 'courseEditRequests']);
        Route::get('dashboard/questions', [DashboardQuestionsController::class, 'index']);
        Route::get('dashboard/questions/categories', [DashboardQuestionsController::class, 'categories']);
        Route::patch('dashboard/questions/{questionId}/status', [DashboardQuestionsController::class, 'updateStatus'])->whereNumber('questionId');
        Route::delete('dashboard/questions/{questionId}', [DashboardQuestionsController::class, 'destroy'])->whereNumber('questionId');
        Route::get('dashboard/quizzes', [DashboardQuizzesController::class, 'index']);
        Route::get('dashboard/quizzes/form/{quizId?}', [DashboardQuizzesController::class, 'showForm'])->whereNumber('quizId');
        Route::post('dashboard/quizzes/form', [DashboardQuizzesController::class, 'saveForm']);
        Route::get('dashboard/quizzes/{quizId}/settings', [DashboardQuizzesController::class, 'showSettings'])->whereNumber('quizId');
        Route::post('dashboard/quizzes/{quizId}/settings', [DashboardQuizzesController::class, 'saveSettings'])->whereNumber('quizId');
        Route::get('dashboard/quizzes/{quizId}/completion-status', [DashboardQuizzesController::class, 'completionStatus'])->whereNumber('quizId');
        Route::get('dashboard/quizzes/{quizId}/questions', [DashboardQuizQuestionsController::class, 'index'])->whereNumber('quizId');
        Route::get('dashboard/quizzes/{quizId}/questions/search', [DashboardQuizQuestionsController::class, 'search'])->whereNumber('quizId');
        Route::post('dashboard/quizzes/{quizId}/questions', [DashboardQuizQuestionsController::class, 'attach'])->whereNumber('quizId');
        Route::put('dashboard/quizzes/{quizId}/questions/order', [DashboardQuizQuestionsController::class, 'updateOrder'])->whereNumber('quizId');
        Route::delete('dashboard/quizzes/{quizId}/questions/{questionId}', [DashboardQuizQuestionsController::class, 'destroy'])
            ->whereNumber(['quizId', 'questionId']);
        Route::patch('dashboard/quizzes/{quizId}/active', [DashboardQuizzesController::class, 'updateActive'])->whereNumber('quizId');
        Route::delete('dashboard/quizzes/{quizId}', [DashboardQuizzesController::class, 'destroy'])->whereNumber('quizId');
        Route::get('dashboard/attach-quizzes/search', [DashboardAttachQuizzesController::class, 'search']);
        Route::post('dashboard/attach-quizzes', [DashboardAttachQuizzesController::class, 'attach']);
        Route::get('dashboard/giftcards', [DashboardGiftcardsController::class, 'index']);
        Route::get('dashboard/favorite-courses', [DashboardPagesController::class, 'favoriteCourses']);
        Route::get('dashboard/flashcards', [DashboardPagesController::class, 'flashcards']);
        Route::get('dashboard/forum/form', [DashboardForumController::class, 'questionForm']);
        Route::get('dashboard/forum/form/{questionId}', [DashboardForumController::class, 'questionForm'])->whereNumber('questionId');
        Route::post('dashboard/forum/form', [DashboardForumController::class, 'saveQuestion']);
        Route::post('dashboard/forum/slug', [DashboardForumController::class, 'formatQuestionSlug']);
        Route::get('dashboard/forum/{questionId}/comments', [DashboardForumController::class, 'questionComments'])->whereNumber('questionId');
        Route::get('dashboard/forum', [DashboardForumController::class, 'questions']);
        Route::get('dashboard/forum-tag-requests/form', [DashboardForumController::class, 'tagRequestForm']);
        Route::get('dashboard/forum-tag-requests/{requestId}/form', [DashboardForumController::class, 'tagRequestForm'])->whereNumber('requestId');
        Route::post('dashboard/forum-tag-requests', [DashboardForumController::class, 'saveTagRequest']);
        Route::get('dashboard/forum-tag-requests', [DashboardForumController::class, 'tagRequests']);
        Route::get('dashboard/forum-subscribed-tags', [DashboardForumSubscribedTagsController::class, 'subscribed']);
        Route::post('dashboard/forum-subscribed-tags', [DashboardForumSubscribedTagsController::class, 'subscribe']);
        Route::delete('dashboard/forum-subscribed-tags', [DashboardForumSubscribedTagsController::class, 'unsubscribeAll']);
        Route::delete('dashboard/forum-subscribed-tags/{tagId}', [DashboardForumSubscribedTagsController::class, 'unsubscribe'])->whereNumber('tagId');
        Route::get('dashboard/forum-tags', [DashboardForumSubscribedTagsController::class, 'systemTags']);
        Route::get('dashboard/forum-tags/suggest', [DashboardForumSubscribedTagsController::class, 'suggest']);
        Route::get('dashboard/refer', [DashboardPagesController::class, 'referHistory']);
        Route::get('dashboard/availability', [DashboardPagesController::class, 'availability']);
        Route::get('dashboard/certificates', [DashboardPagesController::class, 'certificates']);

        Route::post('courses/{course}/enroll', [CourseController::class, 'enroll']);

        Route::get('my/courses', [MyCourseController::class, 'index']);
        Route::get('my/courses/{course}', [MyCourseController::class, 'show']);
        Route::post('my/courses/{course}/start', [MyCourseController::class, 'start']);
        Route::post('my/courses/{course}/progress', [MyCourseController::class, 'updateProgress']);
    });

    Route::middleware(['auth:sanctum', 'admin'])->prefix('admin')->group(function () {
        Route::post('auth/logout', [AdminAuthController::class, 'logout']);
        Route::get('auth/me', [AdminAuthController::class, 'me']);
        Route::get('auth/profile', [AdminAuthController::class, 'profile']);
        Route::put('auth/profile', [AdminAuthController::class, 'updateProfile']);
        Route::post('auth/profile/image', [AdminAuthController::class, 'uploadProfileImage']);
        Route::delete('auth/profile/image', [AdminAuthController::class, 'removeProfileImage']);
        Route::put('auth/password', [AdminAuthController::class, 'updatePassword']);
        Route::get('bootstrap', [AdminBootstrapController::class, 'index']);
        Route::get('page-text/{pageKey}', [AdminPageTextController::class, 'show']);
        Route::get('page-lang-data/{plangId}/lang/{langId}', [AdminPageLangDataController::class, 'langForm'])->whereNumber(['plangId', 'langId']);
        Route::post('page-lang-data/lang-setup', [AdminPageLangDataController::class, 'langSetup']);
        Route::get('themes/{themeId}/form', [AdminThemesController::class, 'form'])->whereNumber('themeId');
        Route::post('themes/setup', [AdminThemesController::class, 'setup']);
        Route::post('themes/{themeId}/activate', [AdminThemesController::class, 'activate'])->whereNumber('themeId');
        Route::delete('themes/{themeId}', [AdminThemesController::class, 'destroy'])->whereNumber('themeId');
        Route::get('currencies/form/{currencyId?}', [AdminCurrencyController::class, 'form'])->whereNumber('currencyId');
        Route::get('currencies/{currencyId}/lang/{langId}', [AdminCurrencyController::class, 'langForm'])->whereNumber(['currencyId', 'langId']);
        Route::post('currencies/setup', [AdminCurrencyController::class, 'setup']);
        Route::post('currencies/lang-setup', [AdminCurrencyController::class, 'langSetup']);
        Route::patch('currencies/{currencyId}/status', [AdminCurrencyController::class, 'changeStatus'])->whereNumber('currencyId');
        Route::put('currencies/order', [AdminCurrencyController::class, 'updateOrder']);
        Route::get('currencies/fixer-config', [AdminCurrencyController::class, 'fixerConfig']);
        Route::post('currencies/fixer-config', [AdminCurrencyController::class, 'setupFixerConfig']);
        Route::post('currencies/sync-rates', [AdminCurrencyController::class, 'syncRates']);
        Route::get('commissions/autocomplete', [AdminCommissionController::class, 'autocomplete']);
        Route::get('commissions/history', [AdminCommissionController::class, 'history']);
        Route::post('commissions/setup', [AdminCommissionController::class, 'setup']);
        Route::get('commissions/{commissionId}', [AdminCommissionController::class, 'show'])->whereNumber('commissionId');
        Route::get('coupons/form', [AdminCouponsController::class, 'form']);
        Route::get('coupons/form/{couponId}', [AdminCouponsController::class, 'form'])->whereNumber('couponId');
        Route::get('coupons/{couponId}/lang/{langId}', [AdminCouponsController::class, 'langForm'])->whereNumber(['couponId', 'langId']);
        Route::post('coupons/setup', [AdminCouponsController::class, 'setup']);
        Route::post('coupons/lang-setup', [AdminCouponsController::class, 'langSetup']);
        Route::get('coupons/uses', [AdminCouponsController::class, 'uses']);
        Route::delete('coupons/{couponId}', [AdminCouponsController::class, 'destroy'])->whereNumber('couponId');
        Route::get('social-platforms/form/{platformId}', [AdminSocialPlatformController::class, 'form'])->whereNumber('platformId');
        Route::post('social-platforms/setup', [AdminSocialPlatformController::class, 'setup']);
        Route::patch('social-platforms/{platformId}/status', [AdminSocialPlatformController::class, 'changeStatus'])->whereNumber('platformId');
        Route::get('slides/form/{slideId?}', [AdminSlidesController::class, 'form'])->whereNumber('slideId');
        Route::post('slides/setup', [AdminSlidesController::class, 'setup']);
        Route::get('slides/{slideId}/media/{langId}', [AdminSlidesController::class, 'mediaForm'])->whereNumber(['slideId', 'langId']);
        Route::post('slides/{slideId}/media/{langId}', [AdminSlidesController::class, 'setupMedia'])->whereNumber(['slideId', 'langId']);
        Route::patch('slides/{slideId}/status', [AdminSlidesController::class, 'changeStatus'])->whereNumber('slideId');
        Route::put('slides/order', [AdminSlidesController::class, 'updateOrder']);
        Route::delete('slides/{slideId}', [AdminSlidesController::class, 'destroy'])->whereNumber('slideId');
        Route::get('payment-methods/settings/{methodId}', [AdminPaymentMethodsController::class, 'settingForm'])->whereNumber('methodId');
        Route::post('payment-methods/settings', [AdminPaymentMethodsController::class, 'settingSetup']);
        Route::get('payment-methods/{methodId}/txnfee', [AdminPaymentMethodsController::class, 'txnfeeForm'])->whereNumber('methodId');
        Route::post('payment-methods/txnfee', [AdminPaymentMethodsController::class, 'txnfeeSetup']);
        Route::patch('payment-methods/{methodId}/status', [AdminPaymentMethodsController::class, 'changeStatus'])->whereNumber('methodId');
        Route::put('payment-methods/order', [AdminPaymentMethodsController::class, 'updateOrder']);
        Route::get('meeting-tools/form/{toolId}', [AdminMeetingToolsController::class, 'form'])->whereNumber('toolId');
        Route::post('meeting-tools/setup', [AdminMeetingToolsController::class, 'setup']);
        Route::patch('meeting-tools/{toolId}/status', [AdminMeetingToolsController::class, 'changeStatus'])->whereNumber('toolId');
        Route::get('dashboard', [AdminDashboardController::class, 'index']);
        Route::get('dashboard/charts', [AdminDashboardController::class, 'charts']);
        Route::get('dashboard/top-lesson-languages', [AdminDashboardController::class, 'topLessonLanguages']);
        Route::get('dashboard/top-class-languages', [AdminDashboardController::class, 'topClassLanguages']);
        Route::get('dashboard/top-course-categories', [AdminDashboardController::class, 'topCourseCategories']);
        Route::get('dashboard/analytics-events', [AdminDashboardController::class, 'analyticsEvents']);
        Route::get('dashboard/analytics-traffic', [AdminDashboardController::class, 'analyticsTraffic']);
        Route::get('configurations/general-settings', [AdminConfigurationController::class, 'generalSettings']);
        Route::patch('configurations/general-settings', [AdminConfigurationController::class, 'updateGeneralSettings']);
        Route::get('configurations/general-settings/lang/{formLangId}', [AdminConfigurationController::class, 'generalSettingsLangForm'])->whereNumber('formLangId');
        Route::patch('configurations/general-settings/lang/{formLangId}', [AdminConfigurationController::class, 'updateGeneralSettingsLangForm'])->whereNumber('formLangId');
        Route::get('configurations/third-party-apis', [AdminConfigurationController::class, 'thirdPartyApis']);
        Route::patch('configurations/third-party-apis', [AdminConfigurationController::class, 'updateThirdPartyApis']);
        Route::get('configurations/google-analytics', [AdminConfigurationController::class, 'googleAnalytics']);
        Route::patch('configurations/google-analytics', [AdminConfigurationController::class, 'updateGoogleAnalytics']);
        Route::get('configurations/forms/{formType}', [AdminConfigurationController::class, 'configurationForm'])->whereNumber('formType');
        Route::patch('configurations/forms/{formType}', [AdminConfigurationController::class, 'updateConfigurationForm'])->whereNumber('formType');
        Route::get('configurations/media', [AdminConfigurationController::class, 'configurationMedia']);
        Route::post('configurations/media', [AdminConfigurationController::class, 'uploadConfigurationMedia']);
        Route::delete('configurations/media', [AdminConfigurationController::class, 'removeConfigurationMedia']);
        Route::post('configurations/pwa-icon', [AdminConfigurationController::class, 'uploadPwaIcon']);
        Route::post('configurations/test-email', [AdminConfigurationController::class, 'testConfigurationEmail']);
        Route::get('reported-issues/{issueId}', [AdminModuleController::class, 'reportedIssueDetail'])->whereNumber('issueId');
        Route::get('modules/{module}', [AdminModuleController::class, 'search']);
        Route::get('lesson-stats/{userId}/logs', [AdminLessonStatsController::class, 'logs'])->whereNumber('userId');
        Route::post('sales-report/regenerate', [AdminSalesReportController::class, 'regenerate']);
        Route::post('sitemap/generate', [AdminSitemapController::class, 'generate']);
        Route::get('sitemap/xml', [AdminSitemapController::class, 'xml']);
        Route::get('sitemap/html', [AdminSitemapController::class, 'html']);
        Route::get('meta-tags/form', [AdminMetaTagsController::class, 'form']);
        Route::post('meta-tags/setup', [AdminMetaTagsController::class, 'setup']);
        Route::get('meta-tags/{metaId}/lang/{langId}', [AdminMetaTagsController::class, 'langForm'])
            ->whereNumber(['metaId', 'langId']);
        Route::put('meta-tags/{metaId}/lang/{langId}', [AdminMetaTagsController::class, 'langSetup'])
            ->whereNumber(['metaId', 'langId']);
        Route::delete('meta-tags/{metaId}', [AdminMetaTagsController::class, 'destroy'])->whereNumber('metaId');
        Route::get('url-rewriting/form', [AdminUrlRewritingController::class, 'form']);
        Route::post('url-rewriting/setup', [AdminUrlRewritingController::class, 'setup']);
        Route::delete('url-rewriting/{id}', [AdminUrlRewritingController::class, 'destroy'])->whereNumber('id');
        Route::get('bots', [AdminBotsController::class, 'show']);
        Route::post('bots/setup', [AdminBotsController::class, 'setup']);
        Route::put('preferences/order', [AdminPreferencesController::class, 'updateOrder']);
        Route::get('preferences/{preferId}', [AdminPreferencesController::class, 'show'])->whereNumber('preferId');
        Route::post('preferences', [AdminPreferencesController::class, 'store']);
        Route::put('preferences/{preferId}', [AdminPreferencesController::class, 'update'])->whereNumber('preferId');
        Route::delete('preferences/{preferId}', [AdminPreferencesController::class, 'destroy'])->whereNumber('preferId');
        Route::put('speak-language-levels/order', [AdminSpeakLanguageLevelsController::class, 'updateOrder']);
        Route::get('speak-language-levels/{slanglvlId}', [AdminSpeakLanguageLevelsController::class, 'show'])->whereNumber('slanglvlId');
        Route::post('speak-language-levels', [AdminSpeakLanguageLevelsController::class, 'store']);
        Route::put('speak-language-levels/{slanglvlId}', [AdminSpeakLanguageLevelsController::class, 'update'])->whereNumber('slanglvlId');
        Route::patch('speak-language-levels/{slanglvlId}/status', [AdminSpeakLanguageLevelsController::class, 'changeStatus'])->whereNumber('slanglvlId');
        Route::delete('speak-language-levels/{slanglvlId}', [AdminSpeakLanguageLevelsController::class, 'destroy'])->whereNumber('slanglvlId');
        Route::put('speak-languages/order', [AdminSpeakLanguagesController::class, 'updateOrder']);
        Route::get('speak-languages/{slangId}', [AdminSpeakLanguagesController::class, 'show'])->whereNumber('slangId');
        Route::post('speak-languages', [AdminSpeakLanguagesController::class, 'store']);
        Route::put('speak-languages/{slangId}', [AdminSpeakLanguagesController::class, 'update'])->whereNumber('slangId');
        Route::patch('speak-languages/{slangId}/status', [AdminSpeakLanguagesController::class, 'changeStatus'])->whereNumber('slangId');
        Route::delete('speak-languages/{slangId}', [AdminSpeakLanguagesController::class, 'destroy'])->whereNumber('slangId');
        Route::put('issue-report-options/order', [AdminIssueReportOptionsController::class, 'updateOrder']);
        Route::get('issue-report-options/{optId}', [AdminIssueReportOptionsController::class, 'show'])->whereNumber('optId');
        Route::post('issue-report-options', [AdminIssueReportOptionsController::class, 'store']);
        Route::put('issue-report-options/{optId}', [AdminIssueReportOptionsController::class, 'update'])->whereNumber('optId');
        Route::patch('issue-report-options/{optId}/status', [AdminIssueReportOptionsController::class, 'changeStatus'])->whereNumber('optId');
        Route::delete('issue-report-options/{optId}', [AdminIssueReportOptionsController::class, 'destroy'])->whereNumber('optId');
        Route::put('forum-report-reasons/order', [AdminForumReportReasonsController::class, 'updateOrder']);
        Route::get('forum-report-reasons/{id}', [AdminForumReportReasonsController::class, 'show'])->whereNumber('id');
        Route::post('forum-report-reasons', [AdminForumReportReasonsController::class, 'store']);
        Route::put('forum-report-reasons/{id}', [AdminForumReportReasonsController::class, 'update'])->whereNumber('id');
        Route::patch('forum-report-reasons/{id}/status', [AdminForumReportReasonsController::class, 'changeStatus'])->whereNumber('id');
        Route::get('forum-tags/{id}', [AdminForumTagsController::class, 'show'])->whereNumber('id');
        Route::post('forum-tags', [AdminForumTagsController::class, 'store']);
        Route::put('forum-tags/{id}', [AdminForumTagsController::class, 'update'])->whereNumber('id');
        Route::patch('forum-tags/{id}/status', [AdminForumTagsController::class, 'changeStatus'])->whereNumber('id');
        Route::delete('forum-tags/{id}', [AdminForumTagsController::class, 'destroy'])->whereNumber('id');
        Route::patch('forum-tags/{id}/restore', [AdminForumTagsController::class, 'restore'])->whereNumber('id');
        Route::get('forum-tag-requests/{id}', [AdminForumTagRequestsController::class, 'show'])->whereNumber('id');
        Route::patch('forum-tag-requests/{id}/status', [AdminForumTagRequestsController::class, 'changeStatus'])->whereNumber('id');
        Route::get('forum-reported-questions/{id}', [AdminForumReportedQuestionsController::class, 'show'])->whereNumber('id');
        Route::post('forum-reported-questions/{id}/action', [AdminForumReportedQuestionsController::class, 'action'])->whereNumber('id');
        Route::get('forum-questions/{id}', [AdminForumQuestionsController::class, 'show'])->whereNumber('id');
        Route::delete('forum-questions/{id}', [AdminForumQuestionsController::class, 'destroy'])->whereNumber('id');
        Route::get('forum-questions/{id}/comments', [AdminForumQuestionsController::class, 'comments'])->whereNumber('id');
        Route::delete('forum-questions/{id}/comments/{commentId}', [AdminForumQuestionsController::class, 'destroyComment'])
            ->whereNumber(['id', 'commentId']);
        Route::get('teach-languages/context', [AdminTeachLanguagesController::class, 'context']);
        Route::get('teach-languages/autocomplete', [AdminTeachLanguagesController::class, 'autocomplete']);
        Route::put('teach-languages/order', [AdminTeachLanguagesController::class, 'updateOrder']);
        Route::get('teach-languages/{tlangId}', [AdminTeachLanguagesController::class, 'show'])->whereNumber('tlangId');
        Route::post('teach-languages', [AdminTeachLanguagesController::class, 'store']);
        Route::put('teach-languages/{tlangId}', [AdminTeachLanguagesController::class, 'update'])->whereNumber('tlangId');
        Route::patch('teach-languages/{tlangId}/status', [AdminTeachLanguagesController::class, 'changeStatus'])->whereNumber('tlangId');
        Route::delete('teach-languages/{tlangId}', [AdminTeachLanguagesController::class, 'destroy'])->whereNumber('tlangId');
        Route::get('teach-languages/{tlangId}/media', [AdminTeachLanguagesController::class, 'mediaForm'])->whereNumber('tlangId');
        Route::post('teach-languages/{tlangId}/media', [AdminTeachLanguagesController::class, 'uploadImage'])->whereNumber('tlangId');
        Route::delete('teach-languages/{tlangId}/media', [AdminTeachLanguagesController::class, 'removeImage'])->whereNumber('tlangId');
        Route::get('teacher-requests/export', [AdminTeacherRequestsController::class, 'export']);
        Route::get('withdraw-requests/export', [AdminWithdrawRequestsController::class, 'export']);
        Route::put('withdraw-requests/{withdrawalId}/status', [AdminWithdrawRequestsController::class, 'updateStatus'])->whereNumber('withdrawalId');
        Route::get('rating-reviews/{reviewId}', [AdminRatingReviewsController::class, 'show'])->whereNumber('reviewId');
        Route::put('rating-reviews/{reviewId}/status', [AdminRatingReviewsController::class, 'updateStatus'])->whereNumber('reviewId');
        Route::get('group-classes/create-form', [AdminGroupClassesController::class, 'createForm']);
        Route::get('group-classes/teacher-autocomplete', [AdminGroupClassesController::class, 'teacherAutocomplete']);
        Route::post('group-classes', [AdminGroupClassesController::class, 'store']);
        Route::get('group-classes/export', [AdminGroupClassesController::class, 'export']);
        Route::get('group-classes/{classId}', [AdminGroupClassesController::class, 'show'])->whereNumber('classId');
        Route::put('group-classes/{classId}', [AdminGroupClassesController::class, 'update'])->whereNumber('classId');
        Route::get('group-classes/{classId}/lang/{langId}', [AdminGroupClassesController::class, 'langForm'])->whereNumber(['classId', 'langId']);
        Route::put('group-classes/{classId}/lang/{langId}', [AdminGroupClassesController::class, 'storeLang'])->whereNumber(['classId', 'langId']);
        Route::get('group-classes/{classId}/media', [AdminGroupClassesController::class, 'mediaForm'])->whereNumber('classId');
        Route::post('group-classes/{classId}/banner', [AdminGroupClassesController::class, 'uploadBanner'])->whereNumber('classId');
        Route::get('group-classes/{classId}/details', [AdminGroupClassesController::class, 'details'])->whereNumber('classId');
        Route::get('group-classes/{classId}/learners', [AdminGroupClassesController::class, 'learners'])->whereNumber('classId');
        Route::get('course-languages/create-form', [AdminCourseLanguagesController::class, 'createForm']);
        Route::get('course-languages/export', [AdminCourseLanguagesController::class, 'export']);
        Route::post('course-languages', [AdminCourseLanguagesController::class, 'store']);
        Route::put('course-languages/order', [AdminCourseLanguagesController::class, 'updateOrder']);
        Route::get('course-languages/{clangId}', [AdminCourseLanguagesController::class, 'show'])->whereNumber('clangId');
        Route::put('course-languages/{clangId}', [AdminCourseLanguagesController::class, 'update'])->whereNumber('clangId');
        Route::patch('course-languages/{clangId}/status', [AdminCourseLanguagesController::class, 'changeStatus'])->whereNumber('clangId');
        Route::delete('course-languages/{clangId}', [AdminCourseLanguagesController::class, 'destroy'])->whereNumber('clangId');
        Route::get('course-languages/{clangId}/lang/{langId}', [AdminCourseLanguagesController::class, 'langForm'])->whereNumber(['clangId', 'langId']);
        Route::put('course-languages/{clangId}/lang/{langId}', [AdminCourseLanguagesController::class, 'storeLang'])->whereNumber(['clangId', 'langId']);
        Route::get('courses/export', [AdminCoursesController::class, 'export']);
        Route::get('courses/search-form', [AdminCoursesController::class, 'searchForm']);
        Route::get('courses/subcategories', [AdminCoursesController::class, 'subcategories']);
        Route::get('courses/course-languages/autocomplete', [AdminCoursesController::class, 'courseLanguageAutocomplete']);
        Route::get('courses/{courseId}/preview', [AdminCoursesController::class, 'preview'])->whereNumber('courseId');
        Route::get('courses/{courseId}/preview/notes', [AdminCoursesController::class, 'previewNotes'])->whereNumber('courseId');
        Route::get('courses/{courseId}/preview/reviews', [AdminCoursesController::class, 'previewReviews'])->whereNumber('courseId');
        Route::get('courses/{courseId}/preview/resources/{resourceId}/download', [AdminCoursesController::class, 'previewDownloadResource'])
            ->whereNumber(['courseId', 'resourceId']);
        Route::get('courses/{courseId}/preview/lectures/{lectureId}', [AdminCoursesController::class, 'previewLecture'])
            ->whereNumber(['courseId', 'lectureId']);
        Route::get('courses/{courseId}', [AdminCoursesController::class, 'show'])->whereNumber('courseId');
        Route::post('courses/{courseId}/preview-bridge', [AdminCoursesController::class, 'previewBridge'])->whereNumber('courseId');
        Route::patch('courses/{courseId}/status', [AdminCoursesController::class, 'updateStatus'])->whereNumber('courseId');
        Route::put('categories/order', [AdminCategoriesController::class, 'updateOrder']);
        Route::get('categories/create-form', [AdminCategoriesController::class, 'createForm']);
        Route::post('categories', [AdminCategoriesController::class, 'store']);
        Route::get('categories/{cateId}', [AdminCategoriesController::class, 'show'])->whereNumber('cateId');
        Route::put('categories/{cateId}', [AdminCategoriesController::class, 'update'])->whereNumber('cateId');
        Route::patch('categories/{cateId}/status', [AdminCategoriesController::class, 'changeStatus'])->whereNumber('cateId');
        Route::delete('categories/{cateId}', [AdminCategoriesController::class, 'destroy'])->whereNumber('cateId');
        Route::get('categories/{cateId}/lang/{langId}', [AdminCategoriesController::class, 'langForm'])->whereNumber(['cateId', 'langId']);
        Route::put('categories/{cateId}/lang/{langId}', [AdminCategoriesController::class, 'storeLang'])->whereNumber(['cateId', 'langId']);
        Route::get('categories/{cateId}/media', [AdminCategoriesController::class, 'mediaForm'])->whereNumber('cateId');
        Route::post('categories/{cateId}/image', [AdminCategoriesController::class, 'uploadImage'])->whereNumber('cateId');
        Route::delete('categories/{cateId}/image', [AdminCategoriesController::class, 'removeImage'])->whereNumber('cateId');
        Route::put('blog-post-categories/order', [AdminBlogPostCategoriesController::class, 'updateOrder']);
        Route::get('blog-post-categories/create-form', [AdminBlogPostCategoriesController::class, 'createForm']);
        Route::post('blog-post-categories', [AdminBlogPostCategoriesController::class, 'store']);
        Route::get('blog-post-categories/{categoryId}', [AdminBlogPostCategoriesController::class, 'show'])->whereNumber('categoryId');
        Route::put('blog-post-categories/{categoryId}', [AdminBlogPostCategoriesController::class, 'update'])->whereNumber('categoryId');
        Route::patch('blog-post-categories/{categoryId}/status', [AdminBlogPostCategoriesController::class, 'changeStatus'])->whereNumber('categoryId');
        Route::delete('blog-post-categories/{categoryId}', [AdminBlogPostCategoriesController::class, 'destroy'])->whereNumber('categoryId');
        Route::get('blog-post-categories/{categoryId}/lang/{langId}', [AdminBlogPostCategoriesController::class, 'langForm'])->whereNumber(['categoryId', 'langId']);
        Route::put('blog-post-categories/{categoryId}/lang/{langId}', [AdminBlogPostCategoriesController::class, 'storeLang'])->whereNumber(['categoryId', 'langId']);
        Route::get('blog-posts/create-form', [AdminBlogPostsController::class, 'createForm']);
        Route::post('blog-posts', [AdminBlogPostsController::class, 'store']);
        Route::get('blog-posts/{postId}', [AdminBlogPostsController::class, 'show'])->whereNumber('postId');
        Route::put('blog-posts/{postId}', [AdminBlogPostsController::class, 'update'])->whereNumber('postId');
        Route::delete('blog-posts/{postId}', [AdminBlogPostsController::class, 'destroy'])->whereNumber('postId');
        Route::get('blog-posts/{postId}/lang/{langId}', [AdminBlogPostsController::class, 'langForm'])->whereNumber(['postId', 'langId']);
        Route::put('blog-posts/{postId}/lang/{langId}', [AdminBlogPostsController::class, 'storeLang'])->whereNumber(['postId', 'langId']);
        Route::get('blog-posts/{postId}/images-form', [AdminBlogPostsController::class, 'imagesForm'])->whereNumber('postId');
        Route::get('blog-posts/{postId}/images', [AdminBlogPostsController::class, 'images'])->whereNumber('postId');
        Route::post('blog-posts/{postId}/images', [AdminBlogPostsController::class, 'uploadImage'])->whereNumber('postId');
        Route::delete('blog-posts/{postId}/images/{fileId}', [AdminBlogPostsController::class, 'deleteImage'])->whereNumber(['postId', 'fileId']);
        Route::get('content-pages/create-form', [AdminContentPagesController::class, 'createForm']);
        Route::post('content-pages', [AdminContentPagesController::class, 'store']);
        Route::get('content-pages/{pageId}', [AdminContentPagesController::class, 'show'])->whereNumber('pageId');
        Route::put('content-pages/{pageId}', [AdminContentPagesController::class, 'update'])->whereNumber('pageId');
        Route::delete('content-pages/{pageId}', [AdminContentPagesController::class, 'destroy'])->whereNumber('pageId');
        Route::get('content-pages/{pageId}/lang/{langId}', [AdminContentPagesController::class, 'langForm'])->whereNumber(['pageId', 'langId']);
        Route::put('content-pages/{pageId}/lang/{langId}', [AdminContentPagesController::class, 'storeLang'])->whereNumber(['pageId', 'langId']);
        Route::post('content-pages/{pageId}/lang/{langId}/background-image', [AdminContentPagesController::class, 'uploadBackgroundImage'])->whereNumber(['pageId', 'langId']);
        Route::delete('content-pages/{pageId}/lang/{langId}/background-image', [AdminContentPagesController::class, 'removeBackgroundImage'])->whereNumber(['pageId', 'langId']);
        Route::get('content-block/types', [AdminContentBlocksController::class, 'types']);
        Route::put('content-block/order', [AdminContentBlocksController::class, 'updateOrder']);
        Route::get('content-block/{blockId}', [AdminContentBlocksController::class, 'show'])->whereNumber('blockId');
        Route::put('content-block/{blockId}', [AdminContentBlocksController::class, 'update'])->whereNumber('blockId');
        Route::patch('content-block/{blockId}/status', [AdminContentBlocksController::class, 'changeStatus'])->whereNumber('blockId');
        Route::get('content-block/{blockId}/lang/{langId}', [AdminContentBlocksController::class, 'langForm'])->whereNumber(['blockId', 'langId']);
        Route::put('content-block/{blockId}/lang/{langId}', [AdminContentBlocksController::class, 'storeLang'])->whereNumber(['blockId', 'langId']);
        Route::get('navigations/{navigationId}/pages', [AdminNavigationsController::class, 'pages'])->whereNumber('navigationId');
        Route::put('navigations/{navigationId}/pages/order', [AdminNavigationsController::class, 'updateLinkOrder'])->whereNumber('navigationId');
        Route::get('navigations/{navigationId}/links/{linkId}', [AdminNavigationsController::class, 'linkForm'])->whereNumber(['navigationId', 'linkId']);
        Route::put('navigations/{navigationId}/links/{linkId}', [AdminNavigationsController::class, 'saveLink'])->whereNumber(['navigationId', 'linkId']);
        Route::get('navigations/{navigationId}/links/{linkId}/lang/{langId}', [AdminNavigationsController::class, 'linkLangForm'])->whereNumber(['navigationId', 'linkId', 'langId']);
        Route::put('navigations/{navigationId}/links/{linkId}/lang/{langId}', [AdminNavigationsController::class, 'saveLinkLang'])->whereNumber(['navigationId', 'linkId', 'langId']);
        Route::patch('navigation-links/{linkId}/status', [AdminNavigationsController::class, 'updateLinkStatus'])->whereNumber('linkId');
        Route::delete('navigation-links/{linkId}', [AdminNavigationsController::class, 'deleteLink'])->whereNumber('linkId');
        Route::get('navigations/{navigationId}', [AdminNavigationsController::class, 'show'])->whereNumber('navigationId');
        Route::put('navigations/{navigationId}', [AdminNavigationsController::class, 'update'])->whereNumber('navigationId');
        Route::patch('navigations/{navigationId}/status', [AdminNavigationsController::class, 'updateStatus'])->whereNumber('navigationId');
        Route::get('navigations/{navigationId}/lang/{langId}', [AdminNavigationsController::class, 'langForm'])->whereNumber(['navigationId', 'langId']);
        Route::put('navigations/{navigationId}/lang/{langId}', [AdminNavigationsController::class, 'storeLang'])->whereNumber(['navigationId', 'langId']);
        Route::get('countries/{countryId}', [AdminCountriesController::class, 'show'])->whereNumber('countryId');
        Route::put('countries/{countryId}', [AdminCountriesController::class, 'update'])->whereNumber('countryId');
        Route::patch('countries/{countryId}/status', [AdminCountriesController::class, 'updateStatus'])->whereNumber('countryId');
        Route::get('countries/{countryId}/lang/{langId}', [AdminCountriesController::class, 'langForm'])->whereNumber(['countryId', 'langId']);
        Route::put('countries/{countryId}/lang/{langId}', [AdminCountriesController::class, 'storeLang'])->whereNumber(['countryId', 'langId']);
        Route::get('states/search-form', [AdminStatesController::class, 'searchForm']);
        Route::get('states/{stateId}', [AdminStatesController::class, 'show'])->whereNumber('stateId');
        Route::put('states/{stateId}', [AdminStatesController::class, 'update'])->whereNumber('stateId');
        Route::patch('states/{stateId}/status', [AdminStatesController::class, 'updateStatus'])->whereNumber('stateId');
        Route::get('states/{stateId}/lang/{langId}', [AdminStatesController::class, 'langForm'])->whereNumber(['stateId', 'langId']);
        Route::put('states/{stateId}/lang/{langId}', [AdminStatesController::class, 'storeLang'])->whereNumber(['stateId', 'langId']);
        Route::put('video-content/order', [AdminVideoContentController::class, 'updateOrder']);
        Route::get('video-content/{contentId}', [AdminVideoContentController::class, 'show'])->whereNumber('contentId');
        Route::put('video-content/{contentId}', [AdminVideoContentController::class, 'update'])->whereNumber('contentId');
        Route::patch('video-content/{contentId}/status', [AdminVideoContentController::class, 'updateStatus'])->whereNumber('contentId');
        Route::delete('video-content/{contentId}', [AdminVideoContentController::class, 'destroy'])->whereNumber('contentId');
        Route::get('video-content/{contentId}/lang/{langId}', [AdminVideoContentController::class, 'langForm'])->whereNumber(['contentId', 'langId']);
        Route::put('video-content/{contentId}/lang/{langId}', [AdminVideoContentController::class, 'storeLang'])->whereNumber(['contentId', 'langId']);
        Route::get('testimonials/{testimonialId}', [AdminTestimonialsController::class, 'show'])->whereNumber('testimonialId');
        Route::put('testimonials/{testimonialId}', [AdminTestimonialsController::class, 'update'])->whereNumber('testimonialId');
        Route::patch('testimonials/{testimonialId}/status', [AdminTestimonialsController::class, 'updateStatus'])->whereNumber('testimonialId');
        Route::delete('testimonials/{testimonialId}', [AdminTestimonialsController::class, 'destroy'])->whereNumber('testimonialId');
        Route::get('testimonials/{testimonialId}/lang/{langId}', [AdminTestimonialsController::class, 'langForm'])->whereNumber(['testimonialId', 'langId']);
        Route::put('testimonials/{testimonialId}/lang/{langId}', [AdminTestimonialsController::class, 'storeLang'])->whereNumber(['testimonialId', 'langId']);
        Route::get('testimonials/{testimonialId}/media', [AdminTestimonialsController::class, 'media'])->whereNumber('testimonialId');
        Route::post('testimonials/{testimonialId}/media', [AdminTestimonialsController::class, 'uploadMedia'])->whereNumber('testimonialId');
        Route::delete('testimonials/{testimonialId}/media', [AdminTestimonialsController::class, 'removeMedia'])->whereNumber('testimonialId');
        Route::get('faq-categories/export', [AdminFaqCategoriesController::class, 'export']);
        Route::put('faq-categories/order', [AdminFaqCategoriesController::class, 'updateOrder']);
        Route::get('faq-categories/{categoryId}', [AdminFaqCategoriesController::class, 'show'])->whereNumber('categoryId');
        Route::put('faq-categories/{categoryId}', [AdminFaqCategoriesController::class, 'update'])->whereNumber('categoryId');
        Route::patch('faq-categories/{categoryId}/status', [AdminFaqCategoriesController::class, 'updateStatus'])->whereNumber('categoryId');
        Route::delete('faq-categories/{categoryId}', [AdminFaqCategoriesController::class, 'destroy'])->whereNumber('categoryId');
        Route::get('faq-categories/{categoryId}/lang/{langId}', [AdminFaqCategoriesController::class, 'langForm'])->whereNumber(['categoryId', 'langId']);
        Route::put('faq-categories/{categoryId}/lang/{langId}', [AdminFaqCategoriesController::class, 'storeLang'])->whereNumber(['categoryId', 'langId']);
        Route::get('faq/export', [AdminFaqController::class, 'export']);
        Route::get('faq/{faqId}', [AdminFaqController::class, 'show'])->whereNumber('faqId');
        Route::put('faq/{faqId}', [AdminFaqController::class, 'update'])->whereNumber('faqId');
        Route::patch('faq/{faqId}/status', [AdminFaqController::class, 'updateStatus'])->whereNumber('faqId');
        Route::delete('faq/{faqId}', [AdminFaqController::class, 'destroy'])->whereNumber('faqId');
        Route::get('faq/{faqId}/lang/{langId}', [AdminFaqController::class, 'langForm'])->whereNumber(['faqId', 'langId']);
        Route::put('faq/{faqId}/lang/{langId}', [AdminFaqController::class, 'storeLang'])->whereNumber(['faqId', 'langId']);
        Route::get('label/export', [AdminLanguageLabelsController::class, 'export']);
        Route::post('label/import', [AdminLanguageLabelsController::class, 'import']);
        Route::get('label/{labelId}', [AdminLanguageLabelsController::class, 'show'])->whereNumber('labelId');
        Route::put('label/{labelId}', [AdminLanguageLabelsController::class, 'update'])->whereNumber('labelId');
        Route::get('email-templates/export', [AdminEmailTemplatesController::class, 'export']);
        Route::get('email-templates/{code}/preview/{langId}', [AdminEmailTemplatesController::class, 'preview'])->whereNumber('langId');
        Route::get('email-templates/{code}/lang/{langId}', [AdminEmailTemplatesController::class, 'langForm'])->whereNumber('langId');
        Route::put('email-templates/{code}/lang/{langId}', [AdminEmailTemplatesController::class, 'storeLang'])->whereNumber('langId');
        Route::patch('email-templates/{code}/status', [AdminEmailTemplatesController::class, 'updateStatus']);
        Route::get('certificates/{code}/preview/{langId}', [AdminCertificatesController::class, 'preview'])->whereNumber('langId');
        Route::get('certificates/{code}/lang/{langId}', [AdminCertificatesController::class, 'langForm'])->whereNumber('langId');
        Route::put('certificates/{code}/lang/{langId}', [AdminCertificatesController::class, 'storeLang'])->whereNumber('langId');
        Route::patch('certificates/{code}/status', [AdminCertificatesController::class, 'updateStatus']);
        Route::post('certificates/{code}/media', [AdminCertificatesController::class, 'uploadMedia']);
        Route::post('abusive-words', [AdminAbusiveWordsController::class, 'store']);
        Route::get('abusive-words/{wordId}', [AdminAbusiveWordsController::class, 'show'])->whereNumber('wordId');
        Route::put('abusive-words/{wordId}', [AdminAbusiveWordsController::class, 'store'])->whereNumber('wordId');
        Route::delete('abusive-words/{wordId}', [AdminAbusiveWordsController::class, 'destroy'])->whereNumber('wordId');
        Route::get('blog-comments/{commentId}', [AdminBlogCommentsController::class, 'show'])->whereNumber('commentId');
        Route::patch('blog-comments/{commentId}/status', [AdminBlogCommentsController::class, 'updateStatus'])->whereNumber('commentId');
        Route::delete('blog-comments/{commentId}', [AdminBlogCommentsController::class, 'destroy'])->whereNumber('commentId');
        Route::get('blog-contributions/{contributionId}', [AdminBlogContributionsController::class, 'show'])->whereNumber('contributionId');
        Route::patch('blog-contributions/{contributionId}/status', [AdminBlogContributionsController::class, 'updateStatus'])->whereNumber('contributionId');
        Route::delete('blog-contributions/{contributionId}', [AdminBlogContributionsController::class, 'destroy'])->whereNumber('contributionId');
        Route::get('affiliate-commissions/autocomplete', [AdminAffiliateCommissionController::class, 'autocomplete']);
        Route::get('affiliate-commissions/history', [AdminAffiliateCommissionController::class, 'history']);
        Route::post('affiliate-commissions', [AdminAffiliateCommissionController::class, 'setup']);
        Route::get('affiliate-commissions/{commissionId}', [AdminAffiliateCommissionController::class, 'show'])->whereNumber('commissionId');
        Route::delete('affiliate-commissions/{commissionId}', [AdminAffiliateCommissionController::class, 'destroy'])->whereNumber('commissionId');
        Route::get('quizzes/export', [AdminQuizzesController::class, 'export']);
        Route::get('quizzes/{quizId}', [AdminQuizzesController::class, 'show'])->whereNumber('quizId');
        Route::get('questions/quiz-categories', [AdminQuestionsController::class, 'quizCategories']);
        Route::get('questions/export', [AdminQuestionsController::class, 'export']);
        Route::get('questions/{questionId}', [AdminQuestionsController::class, 'show'])->whereNumber('questionId');
        Route::get('orders/{orderId}/invoice', [AdminOrdersController::class, 'invoice'])->whereNumber('orderId');
        Route::get('orders/{orderId}', [AdminOrdersController::class, 'show'])->whereNumber('orderId');
        Route::post('orders/{orderId}/cancel', [AdminOrdersController::class, 'cancel'])->whereNumber('orderId');
        Route::post('orders/{orderId}/payment', [AdminOrdersController::class, 'addPayment'])->whereNumber('orderId');
        Route::put('bank-transfers/{payId}/status', [AdminOrdersController::class, 'updateBankTransferStatus'])->whereNumber('payId');
        Route::get('lesson-orders/{lessonId}', [AdminOrdersController::class, 'showLesson'])->whereNumber('lessonId');
        Route::get('class-orders/{classId}', [AdminOrdersController::class, 'showClass'])->whereNumber('classId');
        Route::get('package-orders/{packageId}', [AdminOrdersController::class, 'showPackage'])->whereNumber('packageId');
        Route::get('course-orders/{courseOrderId}', [AdminOrdersController::class, 'showCourse'])->whereNumber('courseOrderId');
        Route::get('giftcard-orders/{orderId}', [AdminOrdersController::class, 'showGiftcard'])->whereNumber('orderId');
        Route::get('order-subscription-plan-orders/{planOrderId}', [AdminOrdersController::class, 'showOrderSubscriptionPlan'])->whereNumber('planOrderId');
        Route::get('gdpr-requests/export', [AdminGdprRequestsController::class, 'export']);
        Route::get('gdpr-requests/{requestId}', [AdminGdprRequestsController::class, 'show'])->whereNumber('requestId');
        Route::put('gdpr-requests/{requestId}/status', [AdminGdprRequestsController::class, 'updateStatus'])->whereNumber('requestId');
        Route::get('admin-users/export', [AdminManageAdminsController::class, 'export']);
        Route::get('admin-users/create', [AdminManageAdminsController::class, 'createForm']);
        Route::post('admin-users', [AdminManageAdminsController::class, 'store']);
        Route::get('admin-users/{adminId}/permissions', [AdminAdminPermissionsController::class, 'show'])->whereNumber('adminId');
        Route::put('admin-users/{adminId}/permissions', [AdminAdminPermissionsController::class, 'update'])->whereNumber('adminId');
        Route::get('admin-users/{adminId}', [AdminManageAdminsController::class, 'show'])->whereNumber('adminId');
        Route::put('admin-users/{adminId}', [AdminManageAdminsController::class, 'update'])->whereNumber('adminId');
        Route::put('admin-users/{adminId}/status', [AdminManageAdminsController::class, 'updateStatus'])->whereNumber('adminId');
        Route::put('admin-users/{adminId}/change-password', [AdminManageAdminsController::class, 'changePassword'])->whereNumber('adminId');
        Route::get('teacher-requests/users/{userId}/qualifications', [AdminTeacherRequestsController::class, 'qualifications'])->whereNumber('userId');
        Route::get('teacher-requests/{requestId}/status-form', [AdminTeacherRequestsController::class, 'statusForm'])->whereNumber('requestId');
        Route::put('teacher-requests/{requestId}/status', [AdminTeacherRequestsController::class, 'updateStatus'])->whereNumber('requestId');
        Route::get('teacher-requests/{requestId}', [AdminTeacherRequestsController::class, 'show'])->whereNumber('requestId');
        Route::get('course-requests/{requestId}', [AdminCourseRequestsController::class, 'show'])->whereNumber('requestId');
        Route::put('course-requests/{requestId}/status', [AdminCourseRequestsController::class, 'updateStatus'])->whereNumber('requestId');
        Route::get('course-edit-requests/{requestId}', [AdminCourseEditRequestsController::class, 'show'])->whereNumber('requestId');
        Route::put('course-edit-requests/{requestId}/status', [AdminCourseEditRequestsController::class, 'updateStatus'])->whereNumber('requestId');
        Route::get('course-refund-requests/{requestId}', [AdminCourseRefundRequestsController::class, 'show'])->whereNumber('requestId');
        Route::get('course-refund-requests/{requestId}/status-form', [AdminCourseRefundRequestsController::class, 'statusForm'])->whereNumber('requestId');
        Route::put('course-refund-requests/{requestId}/status', [AdminCourseRefundRequestsController::class, 'updateStatus'])->whereNumber('requestId');
        Route::get('users/autocomplete', [AdminUsersController::class, 'autocomplete']);
        Route::get('users/export', [AdminUsersController::class, 'export']);
        Route::get('users/create', [AdminUsersController::class, 'create']);
        Route::post('users', [AdminUsersController::class, 'store']);
        Route::get('users/{userId}', [AdminUsersController::class, 'show'])->whereNumber('userId');
        Route::get('users/{userId}/edit', [AdminUsersController::class, 'edit'])->whereNumber('userId');
        Route::put('users/{userId}', [AdminUsersController::class, 'update'])->whereNumber('userId');
        Route::post('users/{userId}/login', [AdminUsersController::class, 'login'])->whereNumber('userId');
        Route::get('users/{userId}/transactions', [AdminUsersController::class, 'transactions'])->whereNumber('userId');
        Route::post('users/{userId}/transactions', [AdminUsersController::class, 'storeTransaction'])->whereNumber('userId');
        Route::get('users/{userId}/addresses', [AdminUsersController::class, 'addresses'])->whereNumber('userId');
        Route::post('users/{userId}/change-password', [AdminUsersController::class, 'changePassword'])->whereNumber('userId');
        Route::patch('users/{userId}/status', [AdminModuleController::class, 'updateUserStatus']);
    });
});
