import type { AdminModuleConfig } from './adminModuleTypes';

export const FORUM_MODULE_CONFIGS: Record<string, AdminModuleConfig> = {
  forum: {
    module: 'forum',
    pageLangKey: 'forum',
    titleKey: 'LBL_All_Questions',
    titleFallback: 'All questions',
    exportable: true,
    canEditPrivilege: 'canEditDiscussionForum',
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_keyword', labelFallback: 'Keyword', type: 'text' },
      {
        name: 'fque_status',
        labelKey: 'LBL_Status',
        labelFallback: 'Status',
        type: 'select',
        options: [
          { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
          { value: '0', labelKey: 'LBL_Drafted', labelFallback: 'Drafted' },
          { value: '1', labelKey: 'LBL_Published', labelFallback: 'Published' },
          { value: '2', labelKey: 'LBL_Resolved', labelFallback: 'Resolved' },
          { value: '3', labelKey: 'LBL_Spammed', labelFallback: 'Spammed' },
        ],
      },
      { name: 'lang_id', labelKey: 'LBL_FORUM_LANGUAGE', labelFallback: 'Language', type: 'language' },
      { name: 'date_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Date from', type: 'date' },
      { name: 'date_till', labelKey: 'LBL_DATE_TO', labelFallback: 'Date to', type: 'date' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SR_NO', labelFallback: 'Sr. No.' },
      { key: 'title', labelKey: 'LBL_Title', labelFallback: 'Title' },
      { key: 'user_name', labelKey: 'LBL_User', labelFallback: 'User' },
      { key: 'language_label', labelKey: 'LBL_FORUM_LANGUAGE', labelFallback: 'Language' },
      { key: 'status_label', labelKey: 'LBL_Status', labelFallback: 'Status' },
      { key: 'added_on', labelKey: 'LBL_Added_On', labelFallback: 'Added on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'forum-reported-questions': {
    module: 'forum-reported-questions',
    pageLangKey: 'forum-reported-questions',
    titleKey: 'LBL_Reported_Questions',
    titleFallback: 'Reported questions',
    exportable: true,
    canEditPrivilege: 'canEditDiscussionForum',
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_keyword', labelFallback: 'Keyword', type: 'text' },
      {
        name: 'status',
        labelKey: 'LBL_Status',
        labelFallback: 'Status',
        type: 'select',
        options: [
          { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
          { value: '0', labelKey: 'LBL_Pending', labelFallback: 'Pending' },
          { value: '1', labelKey: 'LBL_Accepted', labelFallback: 'Accepted' },
          { value: '2', labelKey: 'LBL_Cancelled', labelFallback: 'Cancelled' },
        ],
      },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SR_NO', labelFallback: 'Sr no' },
      { key: 'report_title', labelKey: 'LBL_Report_Title', labelFallback: 'Report reason' },
      { key: 'question_title', labelKey: 'LBL_Question', labelFallback: 'Question' },
      { key: 'reporter_name', labelKey: 'LBL_Reported_By', labelFallback: 'Reported by' },
      { key: 'status_label', labelKey: 'LBL_Status', labelFallback: 'Status' },
      { key: 'added_on', labelKey: 'LBL_ADDED_ON', labelFallback: 'Added on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'forum-tags': {
    module: 'forum-tags',
    pageLangKey: 'forum-tags',
    titleKey: 'LBL_Forum_Tags',
    titleFallback: 'Forum tags',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW_TAG',
    createLabelFallback: 'Add new tag',
    canEditPrivilege: 'canEditDiscussionForum',
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_keyword', labelFallback: 'Keyword', type: 'text' },
      { name: 'lang_id', labelKey: 'LBL_Language', labelFallback: 'Language', type: 'language' },
      {
        name: 'ftag_active',
        labelKey: 'LBL_STATUS',
        labelFallback: 'Status',
        type: 'select',
        options: [
          { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
          { value: '1', labelKey: 'LBL_ACTIVE', labelFallback: 'Active' },
          { value: '0', labelKey: 'LBL_INACTIVE', labelFallback: 'Inactive' },
        ],
      },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SR_NO', labelFallback: 'Sr. No.' },
      { key: 'title', labelKey: 'LBL_Tag_Name', labelFallback: 'Tag name' },
      { key: 'language_label', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'forum-tag-requests': {
    module: 'forum-tag-requests',
    pageLangKey: 'forum-tag-requests',
    titleKey: 'LBL_Requested_Tags',
    titleFallback: 'Requested tags',
    exportable: true,
    canEditPrivilege: 'canEditDiscussionForum',
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_Keyword', labelFallback: 'Keyword', type: 'text' },
      { name: 'lang_id', labelKey: 'LBL_FORUM_LANGUAGE', labelFallback: 'Language', type: 'language' },
      {
        name: 'req_status',
        labelKey: 'LBL_status',
        labelFallback: 'Status',
        type: 'select',
        options: [
          { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
          { value: '0', labelKey: 'LBL_Pending', labelFallback: 'Pending' },
          { value: '1', labelKey: 'LBL_Approved', labelFallback: 'Approved' },
          { value: '2', labelKey: 'LBL_Rejected', labelFallback: 'Rejected' },
        ],
      },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_srNo', labelFallback: 'Sr. No.' },
      { key: 'user_name', labelKey: 'LBL_User', labelFallback: 'User' },
      { key: 'tag_name', labelKey: 'LBL_TAG', labelFallback: 'Tag' },
      { key: 'language_label', labelKey: 'LBL_FORUM_LANGUAGE', labelFallback: 'Language' },
      { key: 'status_label', labelKey: 'LBL_status', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'forum-report-issue-reasons': {
    module: 'forum-report-issue-reasons',
    pageLangKey: 'forum-report-issue-reasons',
    titleKey: 'LBL_Report_Reasons',
    titleFallback: 'Report reasons',
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditDiscussionForum',
    showDragHandle: true,
    tableClassName: 'table--hovered table-dragable',
    hidePagination: true,
    hideSearchPanel: true,
    searchFields: [{ name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' }],
    columns: [
      { key: 'serial', labelKey: 'LBL_srNo', labelFallback: 'Sr. No.' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_title', labelFallback: 'Title' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
};

export const FORUM_MODULES = new Set(Object.keys(FORUM_MODULE_CONFIGS));
