import type { AdminModuleConfig } from './adminModuleTypes';
import { FORUM_MODULE_CONFIGS } from './adminForumModules';
import { ADMIN_ORDER_MODULE_CONFIGS } from './adminOrderModules';
import {
  getPreferencesModuleConfig,
  TEACHER_PREFERENCE_MODULE_CONFIGS,
} from './adminTeacherPreferenceModules';

const blogContributionStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_PENDING', labelFallback: 'Pending' },
  { value: '1', labelKey: 'LBL_APPROVED', labelFallback: 'Approved' },
  { value: '2', labelKey: 'LBL_POSTED', labelFallback: 'Posted' },
  { value: '3', labelKey: 'LBL_REJECTED', labelFallback: 'Rejected' },
];

const blogCommentStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_Approved', labelFallback: 'Approved' },
  { value: '0', labelKey: 'LBL_Pending', labelFallback: 'Pending' },
];

const blogPostStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_PUBLISHED', labelFallback: 'Published' },
  { value: '0', labelKey: 'LBL_IN_DRAFT', labelFallback: 'In draft' },
];

const yesNoOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_YES', labelFallback: 'Yes' },
  { value: '0', labelKey: 'LBL_NO', labelFallback: 'No' },
];

const activeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_ACTIVE', labelFallback: 'Active' },
  { value: '0', labelKey: 'LBL_INACTIVE', labelFallback: 'Inactive' },
];

const userTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_Learner', labelFallback: 'Learner' },
  { value: '2', labelKey: 'LBL_Teacher', labelFallback: 'Teacher' },
  { value: '5', labelKey: 'LBL_Affiliate', labelFallback: 'Affiliate' },
];

const teacherRequestStatusOptions = [
  { value: '', labelKey: 'LBL_ALL', labelFallback: 'All' },
  { value: '0', labelKey: 'LBL_Pending', labelFallback: 'Pending' },
  { value: '1', labelKey: 'LBL_Approved', labelFallback: 'Approved' },
  { value: '2', labelKey: 'LBL_Cancelled_Teacher_Req', labelFallback: 'Cancelled' },
];

const withdrawRequestStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_PENDING', labelFallback: 'Pending' },
  { value: '2', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '3', labelKey: 'LBL_DECLINED', labelFallback: 'Declined' },
  { value: '4', labelKey: 'LBL_PAYOUT_SENT', labelFallback: 'Payout sent' },
  { value: '5', labelKey: 'LBL_PAYOUT_FAILED', labelFallback: 'Payout failed' },
];

const ratingReviewStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'STATUS_PENDING', labelFallback: 'Pending' },
  { value: '1', labelKey: 'STATUS_APPROVED', labelFallback: 'Approved' },
  { value: '2', labelKey: 'STATUS_DECLINED', labelFallback: 'Declined' },
];

const gdprRequestStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_GDPR_PENDING', labelFallback: 'Pending' },
  { value: '2', labelKey: 'LBL_GDPR_DECLINED', labelFallback: 'Declined' },
  { value: '3', labelKey: 'LBL_GDPR_APPROVED', labelFallback: 'Approved' },
];

const groupClassStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_SCHEDULED', labelFallback: 'Scheduled' },
  { value: '2', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '3', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const serviceTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_ONLINE', labelFallback: 'Online' },
  { value: '1', labelKey: 'LBL_OFFLINE', labelFallback: 'Offline' },
];

const classTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_REGULAR', labelFallback: 'Regular' },
  { value: '2', labelKey: 'LBL_PACKAGE', labelFallback: 'Package' },
];

const createdByOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
  { value: '2', labelKey: 'LBL_ADMIN', labelFallback: 'Admin' },
];

const groupClassSearchFields = [
  { name: 'keyword', labelKey: 'LBL_SEARCH_BY_KEYWORD', labelFallback: 'Search by keyword', type: 'text' as const },
  { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' as const },
  { name: 'grpcls_start_datetime', labelKey: 'LBL_START_TIME', labelFallback: 'Start time', type: 'date' as const },
  { name: 'grpcls_end_datetime', labelKey: 'LBL_END_TIME', labelFallback: 'End time', type: 'date' as const },
  { name: 'grpcls_type', labelKey: 'LBL_CLASS_TYPE', labelFallback: 'Class type', type: 'select' as const, options: classTypeOptions },
  { name: 'grpcls_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select' as const, options: serviceTypeOptions },
  { name: 'grpcls_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select' as const, options: groupClassStatusOptions },
  { name: 'created_by_type', labelKey: 'LBL_CREATED_BY', labelFallback: 'Created By', type: 'select' as const, options: createdByOptions },
];

const packageClassSearchFields = [
  { name: 'keyword', labelKey: 'LBL_SEARCH_BY_KEYWORD', labelFallback: 'Search by keyword', type: 'text' as const },
  { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' as const },
  { name: 'grpcls_start_datetime', labelKey: 'LBL_START_TIME', labelFallback: 'Start time', type: 'date' as const },
  { name: 'grpcls_end_datetime', labelKey: 'LBL_END_TIME', labelFallback: 'End time', type: 'date' as const },
  { name: 'grpcls_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select' as const, options: serviceTypeOptions },
  { name: 'grpcls_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select' as const, options: groupClassStatusOptions },
];

const courseRequestStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_PENDING', labelFallback: 'Pending' },
  { value: '1', labelKey: 'LBL_APPROVED', labelFallback: 'Approved' },
  { value: '2', labelKey: 'LBL_DECLINED', labelFallback: 'Declined' },
];

const courseEditRequestStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_EDIT_REQUEST_PENDING', labelFallback: 'Edit request pending' },
  { value: '1', labelKey: 'LBL_EDIT_REQUEST_APPROVED', labelFallback: 'Edit request approved' },
  { value: '2', labelKey: 'LBL_EDIT_REQUEST_DECLINED', labelFallback: 'Edit request declined' },
];

const quizTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_AUTO_GRADED', labelFallback: 'Auto graded' },
  { value: '2', labelKey: 'LBL_NON_GRADED', labelFallback: 'Non graded' },
];

const quizStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_DRAFTED', labelFallback: 'Drafted' },
  { value: '2', labelKey: 'LBL_PUBLISHED', labelFallback: 'Published' },
];

const reportedIssueStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'STATUS_PROGRESS', labelFallback: 'In progress' },
  { value: '2', labelKey: 'STATUS_RESOLVED', labelFallback: 'Resolved' },
  { value: '3', labelKey: 'STATUS_ESCALATED', labelFallback: 'Escalated' },
  { value: '4', labelKey: 'STATUS_CLOSED', labelFallback: 'Closed' },
];

const reportedIssueTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_ONE_TO_ONE', labelFallback: 'One-on-one lesson' },
  { value: '2', labelKey: 'LBL_GROUP_CLASS', labelFallback: 'Group classes/packages' },
];

const reportedIssueSearchFields = [
  { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' as const },
  { name: 'learner', labelKey: 'LBL_LEARNER', labelFallback: 'Learner', type: 'text' as const },
  { name: 'repiss_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select' as const, options: reportedIssueStatusOptions },
  { name: 'order_id', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID', type: 'text' as const },
  { name: 'repiss_record_id', labelKey: 'LBL_CLASS/LESSON_ID', labelFallback: 'Class/Lesson ID', type: 'text' as const },
  { name: 'repiss_record_type', labelKey: 'LBL_TYPE', labelFallback: 'Type', type: 'select' as const, options: reportedIssueTypeOptions },
];

const questionTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_SINGLE_CHOICE', labelFallback: 'Single choice' },
  { value: '2', labelKey: 'LBL_MULTIPLE_CHOICE', labelFallback: 'Multiple choice' },
  { value: '3', labelKey: 'LBL_TEXT', labelFallback: 'Text' },
];

const courseRefundRequestStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_REFUND_PENDING', labelFallback: 'Refund pending' },
  { value: '1', labelKey: 'LBL_REFUND_APPROVED', labelFallback: 'Refund approved' },
  { value: '2', labelKey: 'LBL_REFUND_DECLINED', labelFallback: 'Refund declined' },
];

const courseRequestSearchFields = [
  { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' as const },
  { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' as const },
  { name: 'coapre_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select' as const, options: courseRequestStatusOptions },
  { name: 'start_date', labelKey: 'LBL_DATE_FROM', labelFallback: 'Date from', type: 'date' as const },
  { name: 'end_date', labelKey: 'LBL_DATE_TO', labelFallback: 'Date to', type: 'date' as const },
];

const courseSearchFields = [
  { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' as const },
  { name: 'course_clang', labelKey: 'LBL_COURSE_LANGUAGE', labelFallback: 'Course language', type: 'text' as const },
  { name: 'course_cateid', labelKey: 'LBL_CATEGORY', labelFallback: 'Category', type: 'text' as const },
  { name: 'course_subcateid', labelKey: 'LBL_SUBCATEGORY', labelFallback: 'Subcategory', type: 'text' as const },
  { name: 'course_addedon_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Date from', type: 'date' as const },
  { name: 'course_addedon_till', labelKey: 'LBL_DATE_TO', labelFallback: 'Date to', type: 'date' as const },
];

export const ADMIN_MODULE_CONFIGS: Record<string, AdminModuleConfig> = {
  faq: {
    module: 'faq',
    pageLangKey: 'faq',
    titleKey: 'LBL_MANAGE_FAQS',
    titleFallback: 'Manage FAQs',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditFaq',
    tableClassName: 'table--hovered',
    searchSubmitCol: 4,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', col: 4 },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'identifier', labelKey: 'LBL_FAQ_IDENTIFIER', labelFallback: 'FAQ Identifier' },
      { key: 'title', labelKey: 'LBL_FAQ_TITLE', labelFallback: 'FAQ Title' },
      { key: 'category_name', labelKey: 'LBL_CATEGORY', labelFallback: 'Category' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  slides: {
    module: 'slides',
    pageLangKey: 'slides',
    titleKey: 'LBL_BANNERS',
    titleFallback: 'Banners',
    canEditPrivilege: 'canEditSlides',
    hideSearchPanel: true,
    hidePagination: true,
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr. No.' },
      { key: 'title', labelKey: 'LBL_Title', labelFallback: 'Title' },
      { key: 'active', labelKey: 'LBL_Status', labelFallback: 'Status' },
    ],
  },
  'content-pages': {
    module: 'content-pages',
    pageLangKey: 'content-pages',
    titleKey: 'LBL_CONTENT_PAGES',
    titleFallback: 'Content pages',
    creatable: true,
    canEditPrivilege: 'canEditContentPages',
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    tableClassName: 'table--hovered',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr. No.' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  countries: {
    module: 'countries',
    pageLangKey: 'countries',
    titleKey: 'LBL_COUNTRIES',
    titleFallback: 'Countries',
    exportable: true,
    canEditPrivilege: 'canEditCountries',
    tableClassName: 'table--hovered',
    searchSubmitCol: 4,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', col: 4, inputClass: 'search-input' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'country_flag', labelKey: 'LBL_FLAG', labelFallback: 'Flag' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'country_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'country_code', labelKey: 'LBL_CODE', labelFallback: 'Code' },
      { key: 'country_dial_code', labelKey: 'LBL_DIAL_CODE', labelFallback: 'Dial code' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  states: {
    module: 'states',
    pageLangKey: 'states',
    titleKey: 'LBL_STATES',
    titleFallback: 'States',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD',
    createLabelFallback: 'Add',
    canEditPrivilege: 'canEditStates',
    tableClassName: 'table--hovered',
    searchSubmitCol: 4,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', col: 4, inputClass: 'search-input' },
      { name: 'state_country_id', labelKey: 'LBL_COUNTRY', labelFallback: 'Country', type: 'select', col: 4, options: [] },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'state_identifier', labelKey: 'LBL_STATE_IDENTIFIER', labelFallback: 'State identifier' },
      { key: 'state_code', labelKey: 'LBL_CODE', labelFallback: 'Code' },
      { key: 'state_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'country_identifier', labelKey: 'LBL_COUNTRY', labelFallback: 'Country' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'video-content': {
    module: 'video-content',
    pageLangKey: 'video-content',
    titleKey: 'LBL_VIDEO_CONTENT',
    titleFallback: 'Video content',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditVideoContent',
    hideSearchPanel: true,
    hidePagination: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'dragdrop', labelKey: 'LBL_DRAG', labelFallback: '' },
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'biblecontent_url', labelKey: 'LBLVIDEO_LINK', labelFallback: 'Link' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  testimonials: {
    module: 'testimonials',
    pageLangKey: 'testimonials',
    titleKey: 'LBL_TESTIMONIALS',
    titleFallback: 'Testimonials',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditTestimonial',
    hideSearchPanel: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'testimonial_identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'testimonial_user_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'testimonial_text', labelKey: 'LBL_CONTENT', labelFallback: 'Content' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'faq-categories': {
    module: 'faq-categories',
    pageLangKey: 'faq-categories',
    titleKey: 'LBL_FAQ_CATEGORIES',
    titleFallback: 'FAQ Categories',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditFaqCategory',
    hideSearchPanel: true,
    hidePagination: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'dragdrop', labelKey: 'LBL_DRAG', labelFallback: '' },
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'faqcat_identifier', labelKey: 'LBL_CATEGORY_IDENTIFIER', labelFallback: 'Category identifier' },
      { key: 'faqcat_name', labelKey: 'LBL_CATEGORY_NAME', labelFallback: 'Category name' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'content-block': {
    module: 'content-block',
    pageLangKey: 'content-block',
    titleKey: 'LBL_CONTENT_BLOCKS',
    titleFallback: 'Content blocks',
    canEditPrivilege: 'canEditContentBlocks',
    hideSearchPanel: true,
    hidePagination: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'dragdrop', labelKey: 'LBL_DRAG', labelFallback: '' },
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'identifier', labelKey: 'LBL_PAGE_IDENTIFIER', labelFallback: 'Page Identifier' },
      { key: 'title', labelKey: 'LBL_PAGE_TITLE', labelFallback: 'Page Title' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  navigations: {
    module: 'navigations',
    pageLangKey: 'navigations',
    titleKey: 'LBL_NAVIGATION',
    titleFallback: 'Navigation',
    canEditPrivilege: 'canEditNavigationManagement',
    hideSearchPanel: true,
    hidePagination: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action' },
    ],
  },
  users: {
    module: 'users',
    pageLangKey: 'users',
    titleKey: 'LBL_USERS',
    titleFallback: 'Users',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditUsers',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_NAME_OR_EMAIL', labelFallback: 'Name or Email', type: 'text' },
      { name: 'type', labelKey: 'LBL_USER_TYPE', labelFallback: 'User Type', type: 'select', options: userTypeOptions },
      { name: 'user_verified', labelKey: 'LBL_EMAIL_VERIFIED', labelFallback: 'Email Verified', type: 'select', options: yesNoOptions },
      { name: 'user_featured', labelKey: 'LBL_FEATURED', labelFallback: 'Featured', type: 'select', options: yesNoOptions },
      { name: 'user_active', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: activeOptions },
      { name: 'user_regdate_from', labelKey: 'LBL_REG_DATE_FROM', labelFallback: 'Reg. Date From', type: 'date' },
      { name: 'user_regdate_to', labelKey: 'LBL_REG_DATE_TO', labelFallback: 'Reg. Date To', type: 'date' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'user_image', labelKey: 'LBL_IMAGE', labelFallback: 'Image' },
      { key: 'full_name', labelKey: 'LBL_NAME/ID', labelFallback: 'Name/ID' },
      { key: 'email', labelKey: 'LBL_EMAIL/PHONE', labelFallback: 'Email/Phone' },
      { key: 'type', labelKey: 'LBL_TYPE', labelFallback: 'Type' },
      { key: 'created_at', labelKey: 'LBL_REGISTERED', labelFallback: 'Registered' },
      { key: 'featured', labelKey: 'LBL_FEATURED', labelFallback: 'Featured' },
      { key: 'verified', labelKey: 'LBL_VERIFIED', labelFallback: 'Verified' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'teacher-requests': {
    module: 'teacher-requests',
    titleKey: 'LBL_TEACHER_REQUESTS',
    titleFallback: 'Teacher Requests',
    exportable: true,
    canEditPrivilege: 'canEditTeacherRequests',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: teacherRequestStatusOptions },
      { name: 'date_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Start from', type: 'date' },
      { name: 'date_to', labelKey: 'LBL_DATE_TO', labelFallback: 'End to', type: 'date' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'reference', labelKey: 'LBL_REFERENCE_NUMBER', labelFallback: 'Reference number' },
      { key: 'full_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'email', labelKey: 'LBL_EMAIL/USERNAME', labelFallback: 'Email/Username' },
      { key: 'comments', labelKey: 'LBL_COMMENTS', labelFallback: 'Comments' },
      { key: 'created_at', labelKey: 'LBL_REQUESTED_ON', labelFallback: 'Requested on' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'withdraw-requests': {
    module: 'withdraw-requests',
    titleKey: 'LBL_WITHDRAW_REQUESTS',
    titleFallback: 'Withdraw Requests',
    exportable: true,
    canEditPrivilege: 'canEditWithdrawRequests',
    searchSubmitCol: 6,
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'minprice', labelKey: 'LBL_MIN_PRICE', labelFallback: 'Min price', type: 'text' },
      { name: 'maxprice', labelKey: 'LBL_MAX_PRICE', labelFallback: 'Max price', type: 'text' },
      { name: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: withdrawRequestStatusOptions },
      { name: 'date_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Start from', type: 'date' },
      { name: 'date_to', labelKey: 'LBL_DATE_TO', labelFallback: 'End to', type: 'date' },
    ],
    columns: [
      { key: 'request_number', labelKey: 'LBL_ID', labelFallback: 'ID' },
      { key: 'user_details', labelKey: 'LBL_USER', labelFallback: 'User' },
      { key: 'transaction_fee', labelKey: 'LBL_TXN_FEE', labelFallback: 'Txn fee' },
      { key: 'amount', labelKey: 'LBL_AMOUNT', labelFallback: 'Amount' },
      { key: 'account_details', labelKey: 'LBL_ACCOUNT', labelFallback: 'Account' },
      { key: 'created_at', labelKey: 'LBL_DATE', labelFallback: 'Date' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'rating-reviews': {
    module: 'rating-reviews',
    titleKey: 'LBL_TEACHER_REVIEWS',
    titleFallback: 'Teacher reviews & ratings',
    exportable: true,
    canEditPrivilege: 'canEditTeacherReviews',
    searchSubmitCol: 6,
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'ratrev_user', labelKey: 'LBL_REVIEW_BY', labelFallback: 'Review by', type: 'text' },
      { name: 'ratrev_teacher', labelKey: 'LBL_REVIEW_TO', labelFallback: 'Review to', type: 'text' },
      { name: 'date_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Start from', type: 'date' },
      { name: 'date_to', labelKey: 'LBL_DATE_TO', labelFallback: 'End to', type: 'date' },
      { name: 'ratrev_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: ratingReviewStatusOptions },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'learner_name', labelKey: 'LBL_REVIEW_BY', labelFallback: 'Review by' },
      { key: 'teacher_name', labelKey: 'LBL_REVIEW_TO', labelFallback: 'Review to' },
      { key: 'title', labelKey: 'LBL_REVIEW_DETAIL', labelFallback: 'Review title' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_POSTED', labelFallback: 'Posted' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'gdpr-requests': {
    module: 'gdpr-requests',
    pageLangKey: 'gdpr-requests',
    titleKey: 'LBL_GDPR_REQUESTS',
    titleFallback: 'GDPR requests',
    exportable: true,
    canEditPrivilege: 'canEditGdprRequests',
    searchSubmitCol: 6,
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_Search_By_Keyword', labelFallback: 'Search by keyword', type: 'text' },
      { name: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: gdprRequestStatusOptions },
      { name: 'added_on_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Added on from', type: 'date' },
      { name: 'added_on_to', labelKey: 'LBL_DATE_TO', labelFallback: 'Added on to', type: 'date' },
    ],
    columns: [
      { key: 'id', labelKey: 'LBL_REQ_ID', labelFallback: 'Req ID' },
      { key: 'full_name', labelKey: 'LBL_USER_NAME', labelFallback: 'User name' },
      { key: 'email', labelKey: 'LBL_USER_EMAIL', labelFallback: 'User email' },
      { key: 'reason_short', labelKey: 'LBL_REASON', labelFallback: 'Reason' },
      { key: 'created_at', labelKey: 'LBL_REQUESTED_ON', labelFallback: 'Requested on' },
      { key: 'updated_at', labelKey: 'LBL_UPDATED_ON', labelFallback: 'Updated on' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'admin-users': {
    module: 'admin-users',
    titleKey: 'LBL_Manage_Admins',
    titleFallback: 'Manage Admins',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditAdminUsers',
    tableClassName: 'table--hovered',
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'full_name', labelKey: 'LBL_FULL_NAME', labelFallback: 'Full name' },
      { key: 'username', labelKey: 'LBL_USERNAME', labelFallback: 'Username' },
      { key: 'email', labelKey: 'LBL_EMAIL', labelFallback: 'Email' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'group-classes': {
    module: 'group-classes',
    pageLangKey: 'group-classes',
    titleKey: 'LBL_GROUP_CLASSES',
    titleFallback: 'Group classes',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditGroupClasses',
    createLabelKey: 'LBL_ADD_CLASS',
    createLabelFallback: 'Add class',
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: groupClassSearchFields,
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'title', labelKey: 'LBL_Class_Title', labelFallback: 'Class title' },
      { key: 'class_type_label', labelKey: 'LBL_TYPE', labelFallback: 'Type' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'teacher_name', labelKey: 'LBL_Teacher', labelFallback: 'Teacher' },
      { key: 'created_by_label', labelKey: 'LBL_Created_By', labelFallback: 'Created by' },
      { key: 'entry_fee', labelKey: 'LBL_Entry_Fee', labelFallback: 'Entry fee' },
      { key: 'start_at', labelKey: 'LBL_START_TIME', labelFallback: 'Start time' },
      { key: 'end_at', labelKey: 'LBL_END_TIME', labelFallback: 'End time' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'package-classes': {
    module: 'package-classes',
    pageLangKey: 'package-classes',
    titleKey: 'LBL_PACKAGE_CLASSES',
    titleFallback: 'Package classes',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditPackageClasses',
    createLabelKey: 'LBL_ADD_PACKAGE_CLASS',
    createLabelFallback: 'Add Package Class',
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: packageClassSearchFields,
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'title', labelKey: 'LBL_PACKAGE', labelFallback: 'Package' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'start_at', labelKey: 'LBL_START_TIME', labelFallback: 'Start time' },
      { key: 'end_at', labelKey: 'LBL_END_TIME', labelFallback: 'End time' },
      { key: 'created_at', labelKey: 'LBL_CREATED', labelFallback: 'Created' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'page-lang-data': {
    module: 'page-lang-data',
    titleKey: 'LBL_Page_Language_Data',
    titleFallback: 'Page language data',
    pageLangKey: 'page-lang-data',
    canEditPrivilege: 'canEditPageLangData',
    tableClassName: 'table-dashed',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'page_key', labelKey: 'LBL_PAGE_KEY', labelFallback: 'Page key' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  themes: {
    module: 'themes',
    titleKey: 'LBL_Theme_Management',
    titleFallback: 'Theme management',
    pageLangKey: 'themes',
    canEditPrivilege: 'canEditThemeManagement',
    hidePagination: false,
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [],
  },
  'currency-management': {
    module: 'currency-management',
    titleKey: 'LBL_Currency_Management',
    titleFallback: 'Currency management',
    pageLangKey: 'currency-management',
    canEditPrivilege: 'canEditCurrencyManagement',
    columns: [],
  },
  'social-platform': {
    module: 'social-platform',
    titleKey: 'LBL_SOCIAL_PLATFORMS',
    titleFallback: 'Social platforms',
    pageLangKey: 'social-platform',
    canEditPrivilege: 'canEditSocialPlatforms',
    hidePagination: true,
    hideSearchPanel: true,
    columns: [],
  },
  'payment-methods': {
    module: 'payment-methods',
    titleKey: 'LBL_Payment_Methods',
    titleFallback: 'Payment methods',
    pageLangKey: 'payment-methods',
    canEditPrivilege: 'canEditPaymentMethods',
    hidePagination: true,
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [],
  },
  'meeting-tools': {
    module: 'meeting-tools',
    titleKey: 'LBL_Meeting_Tools',
    titleFallback: 'Meeting tools',
    pageLangKey: 'meeting-tools',
    canEditPrivilege: 'canEditMeetingTool',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_Keyword', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
      { name: 'metool_status', labelKey: 'LBL_Status', labelFallback: 'Status', type: 'select', options: activeOptions },
    ],
    columns: [],
  },
  commission: {
    module: 'commission',
    titleKey: 'LBL_Commission_Settings',
    titleFallback: 'Commission settings',
    pageLangKey: 'commission',
    canEditPrivilege: 'canEditCommissionSettings',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [],
  },
  coupons: {
    module: 'coupons',
    titleKey: 'LBL_Discount_Coupons',
    titleFallback: 'Discount coupons',
    pageLangKey: 'coupons',
    canEditPrivilege: 'canEditDiscountCoupons',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
      { name: 'coupon_active', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: activeOptions },
      { name: 'coupon_expire', labelKey: 'LBL_EXPIRE', labelFallback: 'Expire', type: 'select', options: yesNoOptions },
    ],
    columns: [],
  },
  'affiliate-commission': {
    module: 'affiliate-commission',
    titleKey: 'LBL_AFFILIATE_COMMISSION',
    titleFallback: 'Affiliate commission',
    pageLangKey: 'affiliate-commission',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [],
  },
  'blog-contributions': {
    module: 'blog-contributions',
    titleKey: 'LBL_Blog_Contributions',
    titleFallback: 'Blog contributions',
    pageLangKey: 'blog-contributions',
    exportable: true,
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
      {
        name: 'bcontributions_status',
        labelKey: 'LBL_Contribution_Status',
        labelFallback: 'Contribution status',
        type: 'select',
        options: blogContributionStatusOptions,
      },
    ],
    columns: [],
  },
  'blog-comments': {
    module: 'blog-comments',
    titleKey: 'LBL_Blog_Comments',
    titleFallback: 'Blog comments',
    pageLangKey: 'blog-comments',
    exportable: true,
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
      {
        name: 'bpcomment_approved',
        labelKey: 'LBL_Comment_Status',
        labelFallback: 'Comment status',
        type: 'select',
        options: blogCommentStatusOptions,
      },
    ],
    columns: [],
  },
  'blog-posts': {
    module: 'blog-posts',
    titleKey: 'LBL_Blog_Posts',
    titleFallback: 'Blog Posts',
    pageLangKey: 'blog-posts',
    exportable: true,
    canEditPrivilege: 'canEditBlogPosts',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
      {
        name: 'post_published',
        labelKey: 'LBL_Post_Status',
        labelFallback: 'Post status',
        type: 'select',
        options: blogPostStatusOptions,
      },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'published', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_POSTED_ON', labelFallback: 'Posted On' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  orders: ADMIN_ORDER_MODULE_CONFIGS.orders,
  lessons: ADMIN_ORDER_MODULE_CONFIGS.lessons,
  subscriptions: ADMIN_ORDER_MODULE_CONFIGS.subscriptions,
  classes: ADMIN_ORDER_MODULE_CONFIGS.classes,
  'course-orders': ADMIN_ORDER_MODULE_CONFIGS['course-orders'],
  packages: ADMIN_ORDER_MODULE_CONFIGS.packages,
  giftcards: ADMIN_ORDER_MODULE_CONFIGS.giftcards,
  wallet: ADMIN_ORDER_MODULE_CONFIGS.wallet,
  'order-subscription-plans': ADMIN_ORDER_MODULE_CONFIGS['order-subscription-plans'],
  courses: {
    module: 'courses',
    pageLangKey: 'courses',
    titleKey: 'LBL_COURSES',
    titleFallback: 'Courses',
    exportable: true,
    canEditPrivilege: 'canEditCourses',
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: courseSearchFields,
    columns: [
      { key: 'id', labelKey: 'LBL_ID', labelFallback: 'ID' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'category_name', labelKey: 'LBL_CATEGORY', labelFallback: 'Category' },
      { key: 'subcategory_name', labelKey: 'LBL_SUBCATEGORY', labelFallback: 'Subcategory' },
      { key: 'published_at', labelKey: 'LBL_PUBLISHED_ON', labelFallback: 'Published On' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'course-languages': {
    module: 'course-languages',
    pageLangKey: 'course-languages',
    titleKey: 'LBL_COURSE_LANGUAGES',
    titleFallback: 'Course languages',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditCourseLanguage',
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'identifier', labelKey: 'LBL_COURSE_LANGUAGE_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_COURSE_LANGUAGE_NAME', labelFallback: 'Name' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  categories: {
    module: 'categories',
    pageLangKey: 'categories',
    titleKey: 'LBL_CATEGORIES',
    titleFallback: 'Categories',
    exportable: true,
    creatable: true,
    canEditPrivilege: 'canEditCourseCategories',
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
      { key: 'title', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'subcategories', labelKey: 'LBL_SUB_CATEGORIES', labelFallback: 'Sub categories' },
      { key: 'records', labelKey: 'LBL_RECORDS', labelFallback: 'Records' },
      { key: 'featured', labelKey: 'LBL_FEATURED', labelFallback: 'Featured' },
      { key: 'updated_at', labelKey: 'LBL_UPDATED', labelFallback: 'Updated' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'course-requests': {
    module: 'course-requests',
    pageLangKey: 'course-requests',
    titleKey: 'LBL_COURSE_APPROVAL_REQUESTS',
    titleFallback: 'Approval requests',
    exportable: true,
    canEditPrivilege: 'canEditCourseRequests',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: courseRequestSearchFields,
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'title', labelKey: 'LBL_COURSE_NAME', labelFallback: 'Course name' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER_NAME', labelFallback: 'Teacher name' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_REQUESTED_ON', labelFallback: 'Requested on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'course-edit-requests': {
    module: 'course-edit-requests',
    pageLangKey: 'course-edit-requests',
    titleKey: 'LBL_COURSE_EDIT_REQUESTS',
    titleFallback: 'Edit requests',
    exportable: true,
    canEditPrivilege: 'canEditCourseEditRequests',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'coedre_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: courseEditRequestStatusOptions },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'title', labelKey: 'LBL_COURSE_NAME', labelFallback: 'Course name' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER_NAME', labelFallback: 'Teacher name' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_REQUESTED_ON', labelFallback: 'Requested on' },
      { key: 'expired_at', labelKey: 'LBL_EXPIRED_ON', labelFallback: 'Expired on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'course-refund-requests': {
    module: 'course-refund-requests',
    pageLangKey: 'course-refund-requests',
    titleKey: 'LBL_COURSE_REFUND_REQUESTS',
    titleFallback: 'Refund requests',
    exportable: true,
    canEditPrivilege: 'canEditCourseRefundRequests',
    searchSubmitCol: 3,
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_COURSE_TITLE_OR_SUBTITLE',
        placeholderFallback: 'Search by course title or subtitle',
      },
      { name: 'learner', labelKey: 'LBL_LEARNER', labelFallback: 'Learner', type: 'text' },
      { name: 'corere_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: courseRefundRequestStatusOptions },
      { name: 'start_date', labelKey: 'LBL_DATE_FROM', labelFallback: 'Start from', type: 'date' },
      { name: 'end_date', labelKey: 'LBL_DATE_TO', labelFallback: 'End to', type: 'date' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'title', labelKey: 'LBL_COURSE_NAME', labelFallback: 'Course name' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER_NAME', labelFallback: 'Learner name' },
      { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_REQUESTED_ON', labelFallback: 'Requested on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  questions: {
    module: 'questions',
    pageLangKey: 'questions',
    titleKey: 'LBL_QUESTIONS',
    titleFallback: 'Questions',
    exportable: true,
    tableClassName: 'table--hovered',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_TITLE', labelFallback: 'Title', type: 'text' },
      { name: 'ques_cate_id', labelKey: 'LBL_CATEGORY', labelFallback: 'Category', type: 'text' },
      { name: 'ques_subcate_id', labelKey: 'LBL_SUBCATEGORY', labelFallback: 'Subcategory', type: 'text' },
      { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' },
      { name: 'ques_type', labelKey: 'LBL_TYPE', labelFallback: 'Type', type: 'select', options: questionTypeOptions },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'title', labelKey: 'LBL_QUESTION_TITLE', labelFallback: 'Question title' },
      { key: 'type_label', labelKey: 'LBL_TYPE', labelFallback: 'Type' },
      { key: 'category_name', labelKey: 'LBL_CATEGORY', labelFallback: 'Category' },
      { key: 'subcategory_name', labelKey: 'LBL_SUBCATEGORY', labelFallback: 'Subcategory' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'created_at', labelKey: 'LBL_ADDED_ON', labelFallback: 'Added on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  quizzes: {
    module: 'quizzes',
    pageLangKey: 'quizzes',
    titleKey: 'LBL_QUIZZES',
    titleFallback: 'Quizzes',
    exportable: true,
    tableClassName: 'table--hovered',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_TITLE', labelFallback: 'Title', type: 'text' },
      { name: 'teacher', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher', type: 'text' },
      { name: 'quiz_type', labelKey: 'LBL_TYPE', labelFallback: 'Type', type: 'select', options: quizTypeOptions },
      { name: 'quiz_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: quizStatusOptions },
      { name: 'quiz_active', labelKey: 'LBL_ACTIVE', labelFallback: 'Active', type: 'select', options: yesNoOptions },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_Sr._No', labelFallback: 'Sr. No' },
      { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'type_label', labelKey: 'LBL_TYPE', labelFallback: 'Type' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'questions_count', labelKey: 'LBL_NO._OF_QUESTIONS', labelFallback: 'No. of questions' },
      { key: 'duration_label', labelKey: 'LBL_DURATION', labelFallback: 'Duration' },
      { key: 'attempts', labelKey: 'LBL_ATTEMPTS', labelFallback: 'Attempts' },
      { key: 'passmark_label', labelKey: 'LBL_PASS_PERCENT', labelFallback: 'Pass percent' },
      { key: 'active_label', labelKey: 'LBL_ACTIVE', labelFallback: 'Active' },
      { key: 'status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'created_at', labelKey: 'LBL_ADDED_ON', labelFallback: 'Added on' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'reported-issues': {
    module: 'reported-issues',
    pageLangKey: 'reported-issues',
    titleKey: 'LBL_ALL_REPORTED_ISSUES',
    titleFallback: 'All reported issues',
    exportable: true,
    tableClassName: 'table--hovered',
    searchFields: reportedIssueSearchFields,
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr. No' },
      { key: 'record_type_label', labelKey: 'LBL_TYPE', labelFallback: 'Type' },
      { key: 'repiss_record_id', labelKey: 'LBL_CLASS/LESSON_ID', labelFallback: 'Class/Lesson ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'repiss_title', labelKey: 'LBL_Issue', labelFallback: 'Issue' },
      { key: 'reporter_name', labelKey: 'LBL_Reported_By', labelFallback: 'Reported by' },
      { key: 'reported_on', labelKey: 'LBL_Reported_On', labelFallback: 'Reported on' },
      { key: 'status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'url-rewriting': {
    module: 'url-rewriting',
    pageLangKey: 'url-rewriting',
    titleKey: 'LBL_URL_REWRITING',
    titleFallback: 'Url rewriting',
    exportable: true,
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditSeoUrl',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_Keyword', labelFallback: 'Keyword', type: 'text' },
      { name: 'seourl_lang_id', labelKey: 'LBL_Language', labelFallback: 'Language', type: 'select', options: [] },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr. No.' },
      { key: 'seourl_original', labelKey: 'LBL_Original', labelFallback: 'Original' },
      { key: 'seourl_custom', labelKey: 'LBL_Custom', labelFallback: 'Custom' },
      { key: 'seourl_httpcode', labelKey: 'LBL_httpcode', labelFallback: 'HTTP code' },
      { key: 'language_name', labelKey: 'LBL_Language', labelFallback: 'Language' },
      { key: 'action', labelKey: 'LBL_Action', labelFallback: 'Action', align: 'right' },
    ],
  },
  label: {
    module: 'label',
    pageLangKey: 'label',
    titleKey: 'LBL_LANGUAGE_LABEL',
    titleFallback: 'Language Labels',
    exportable: true,
    importable: true,
    canEditPrivilege: 'canEditLanguageLabel',
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', inputClass: 'search-input' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'label_key', labelKey: 'LBL_Key', labelFallback: 'Key' },
      { key: 'label_caption', labelKey: 'LBL_Caption', labelFallback: 'Caption' },
      { key: 'action', labelKey: 'LBL_Action', labelFallback: 'Action', align: 'right' },
    ],
  },
  'email-templates': {
    module: 'email-templates',
    pageLangKey: 'email-templates',
    titleKey: 'LBL_EMAIL_TEMPLATES',
    titleFallback: 'Email Templates',
    exportable: true,
    canEditPrivilege: 'canEditEmailTemplates',
    tableClassName: 'table--hovered',
    searchSubmitCol: 6,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text', col: 6, inputClass: 'search-input' },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'etpl_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'etpl_subject', labelKey: 'LBL_SUBJECT', labelFallback: 'Language' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'abusive-words': {
    module: 'abusive-words',
    pageLangKey: 'abusive-words',
    titleKey: 'LBL_RESTRICTED_KEYWORDS_ABUSIVE',
    titleFallback: 'Restricted keywords (Abusive)',
    creatable: true,
    createLabelKey: 'LBL_ADD_NEW',
    createLabelFallback: 'Add new',
    canEditPrivilege: 'canEditAbusiveWords',
    tableClassName: 'table--hovered',
    searchSubmitCol: 6,
    searchFields: [
      {
        name: 'abusive_keyword',
        labelKey: 'LBL_SEARCH_BY_ABUSIVE_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        col: 6,
        inputClass: 'search-input',
      },
    ],
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no' },
      { key: 'abusive_keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  certificates: {
    module: 'certificates',
    pageLangKey: 'certificates',
    titleKey: 'LBL_COURSE_CERTIFICATE',
    titleFallback: 'Course Certificate',
    canEditPrivilege: 'canEditCertificates',
    hideSearchPanel: true,
    hidePagination: true,
    tableClassName: 'table--hovered',
    columns: [
      { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr no.' },
      { key: 'certpl_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
      { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
};

export function getAdminModuleConfig(module: string, typeId?: string): AdminModuleConfig {
  if (module === 'preferences' && typeId) {
    return getPreferencesModuleConfig(typeId);
  }

  return (
    ADMIN_MODULE_CONFIGS[module] ??
    TEACHER_PREFERENCE_MODULE_CONFIGS[module] ??
    FORUM_MODULE_CONFIGS[module] ?? {
      module,
      titleKey: 'LBL_LISTING',
      titleFallback: module.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      columns: [
        { key: 'serial', labelKey: 'LBL_SRNO', labelFallback: 'Sr.No' },
        { key: 'title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
        { key: 'identifier', labelKey: 'LBL_IDENTIFIER', labelFallback: 'Identifier' },
        { key: 'full_name', labelKey: 'LBL_NAME', labelFallback: 'Name' },
        { key: 'status', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
        { key: 'active', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
        { key: 'created_at', labelKey: 'LBL_DATE', labelFallback: 'Date' },
      ],
      searchFields: [{ name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' }],
    }
  );
}
