import type { AdminModuleConfig } from './adminModuleTypes';

const paymentStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_UNPAID', labelFallback: 'Unpaid' },
  { value: '1', labelKey: 'LBL_IS_PAID', labelFallback: 'Paid' },
];

const orderStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_INPROCESS', labelFallback: 'In process' },
  { value: '2', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '3', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const orderTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_LESSON', labelFallback: 'Lesson' },
  { value: '2', labelKey: 'LBL_RECURRING_LESSONS', labelFallback: 'Recurring lessons' },
  { value: '3', labelKey: 'LBL_GROUP_CLASSES', labelFallback: 'Group classes' },
  { value: '4', labelKey: 'LBL_CLASS_PACKAGES', labelFallback: 'Class packages' },
  { value: '5', labelKey: 'LBL_COURSE_PURCHASED', labelFallback: 'Course purchased' },
  { value: '6', labelKey: 'LBL_WALLET_RECHARGE', labelFallback: 'Wallet recharge' },
  { value: '7', labelKey: 'LBL_GIFTCARD_PURCHASED', labelFallback: 'Giftcard purchased' },
  { value: '18', labelKey: 'LBL_SUBSCRIPTION_PLAN', labelFallback: 'Subscription plan' },
];

const serviceTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_ONLINE', labelFallback: 'Online' },
  { value: '1', labelKey: 'LBL_OFFLINE', labelFallback: 'Offline' },
];

const lessonStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_UNSCHEDULED', labelFallback: 'Unscheduled' },
  { value: '2', labelKey: 'LBL_SCHEDULED', labelFallback: 'Scheduled' },
  { value: '3', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '4', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const subscriptionStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_ACTIVE', labelFallback: 'Active' },
  { value: '2', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '3', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const classStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_SCHEDULED', labelFallback: 'Scheduled' },
  { value: '2', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '3', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const courseOrderStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_PENDING', labelFallback: 'Pending' },
  { value: '2', labelKey: 'LBL_IN_PROGRESS', labelFallback: 'In progress' },
  { value: '3', labelKey: 'LBL_COMPLETED', labelFallback: 'Completed' },
  { value: '4', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const lessonTypeOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '1', labelKey: 'LBL_REGULAR', labelFallback: 'Regular' },
  { value: '2', labelKey: 'LBL_FREE_TRIAL', labelFallback: 'Free trial' },
];

const giftcardStatusOptions = [
  { value: '', labelKey: 'LBL_SELECT', labelFallback: 'Select' },
  { value: '0', labelKey: 'LBL_UNUSED', labelFallback: 'Unused' },
  { value: '1', labelKey: 'LBL_USED', labelFallback: 'Used' },
  { value: '2', labelKey: 'LBL_CANCELLED', labelFallback: 'Cancelled' },
];

const orderDateSearchFields = [
  { name: 'date_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Date from', type: 'date' as const },
  { name: 'date_to', labelKey: 'LBL_DATE_TO', labelFallback: 'Date to', type: 'date' as const },
];

const lessonDateSearchFields = [
  { name: 'order_addedon_from', labelKey: 'LBL_DATE_FROM', labelFallback: 'Date from', type: 'date' as const },
  { name: 'order_addedon_till', labelKey: 'LBL_DATE_TO', labelFallback: 'Date to', type: 'date' as const },
];

export const ADMIN_ORDER_MODULE_CONFIGS: Record<string, AdminModuleConfig> = {
  orders: {
    module: 'orders',
    pageLangKey: 'orders',
    titleKey: 'LBL_ALL_ORDERS',
    titleFallback: 'All Orders',
    exportable: true,
    canEditPrivilege: 'canEditOrders',
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'order_user', labelKey: 'LBL_USER', labelFallback: 'User', type: 'text' },
      { name: 'order_type', labelKey: 'LBL_ORDER_TYPE', labelFallback: 'Order type', type: 'select', options: orderTypeOptions },
      { name: 'service_type', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select', options: serviceTypeOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'order_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: orderStatusOptions },
      ...orderDateSearchFields,
    ],
    columns: [
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'learner_full_name', labelKey: 'LBL_USER_NAME', labelFallback: 'User name' },
      { key: 'order_type_label', labelKey: 'LBL_ORDER_TYPE', labelFallback: 'Order type' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'order_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  lessons: {
    module: 'lessons',
    pageLangKey: 'lessons',
    titleKey: 'LBL_LESSONS_ORDERS',
    titleFallback: 'Lessons Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_KEYWORD',
        placeholderFallback: 'Search by keyword',
      },
      { name: 'ordles_tlang', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language', type: 'text' },
      { name: 'ordles_type', labelKey: 'LBL_LESSON_TYPE', labelFallback: 'Lesson type', type: 'select', options: lessonTypeOptions },
      { name: 'ordles_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select', options: serviceTypeOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'ordles_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: lessonStatusOptions },
      ...lessonDateSearchFields,
    ],
    columns: [
      { key: 'ordles_id', labelKey: 'LBL_LESSON_ID', labelFallback: 'Lesson ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'ordles_language_name', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'ordles_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordles_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  subscriptions: {
    module: 'subscriptions',
    pageLangKey: 'subscriptions',
    titleKey: 'LBL_RECURRING_LESSONS',
    titleFallback: 'Recurring lessons',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_KEYWORD',
        placeholderFallback: 'Search by keyword',
      },
      { name: 'ordsub_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select', options: serviceTypeOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'ordsub_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: subscriptionStatusOptions },
      { name: 'ordsub_startdate', labelKey: 'LBL_START_DATE', labelFallback: 'Start date', type: 'date' },
      { name: 'ordsub_enddate', labelKey: 'LBL_END_DATE', labelFallback: 'End date', type: 'date' },
    ],
    columns: [
      { key: 'ordsub_id', labelKey: 'LBL_ID', labelFallback: 'ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'ordsub_startdate', labelKey: 'LBL_START_DATE', labelFallback: 'Start date' },
      { key: 'ordsub_enddate', labelKey: 'LBL_END_DATE', labelFallback: 'End date' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'order_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordsub_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  classes: {
    module: 'classes',
    pageLangKey: 'classes',
    titleKey: 'LBL_CLASSES_ORDERS',
    titleFallback: 'Classes Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_KEYWORD',
        placeholderFallback: 'Search by keyword',
      },
      { name: 'ordcls_tlang', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language', type: 'text' },
      { name: 'grpcls_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select', options: serviceTypeOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'ordcls_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: classStatusOptions },
      ...lessonDateSearchFields,
    ],
    columns: [
      { key: 'ordcls_id', labelKey: 'LBL_CLASS_ID', labelFallback: 'Class ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'grpcls_language_name', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'ordcls_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordcls_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'course-orders': {
    module: 'course-orders',
    pageLangKey: 'course-orders',
    titleKey: 'LBL_COURSE_ORDERS',
    titleFallback: 'Course Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_COURSE_TITLE,_TEACHER,_LEARNER,_ORDER_ID',
        placeholderFallback: 'Search by course title, teacher, learner, order id',
      },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'ordcrs_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: courseOrderStatusOptions },
      ...lessonDateSearchFields,
    ],
    columns: [
      { key: 'ordcrs_id', labelKey: 'LBL_ID', labelFallback: 'ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'course_title', labelKey: 'LBL_TITLE', labelFallback: 'Title' },
      { key: 'ordcrs_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_created', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordcrs_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  packages: {
    module: 'packages',
    pageLangKey: 'packages',
    titleKey: 'LBL_PACKAGES_ORDERS',
    titleFallback: 'Packages Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      {
        name: 'keyword',
        labelKey: 'LBL_KEYWORD',
        labelFallback: 'Keyword',
        type: 'text',
        placeholderKey: 'LBL_SEARCH_BY_KEYWORD',
        placeholderFallback: 'Search by keyword',
      },
      { name: 'ordcls_tlang', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language', type: 'text' },
      { name: 'ordpkg_offline', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type', type: 'select', options: serviceTypeOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
      { name: 'ordpkg_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: subscriptionStatusOptions },
      ...lessonDateSearchFields,
    ],
    columns: [
      { key: 'ordpkg_id', labelKey: 'LBL_PACKAGE_ID', labelFallback: 'Package ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'teacher_name', labelKey: 'LBL_TEACHER', labelFallback: 'Teacher' },
      { key: 'grpcls_language_name', labelKey: 'LBL_LANGUAGE', labelFallback: 'Language' },
      { key: 'service_type_label', labelKey: 'LBL_SERVICE_TYPE', labelFallback: 'Service type' },
      { key: 'order_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordpkg_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  giftcards: {
    module: 'giftcards',
    pageLangKey: 'giftcards',
    titleKey: 'LBL_GIFT_CARD_ORDERS',
    titleFallback: 'Gift Card Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'giftcard_status', labelKey: 'LBL_STATUS', labelFallback: 'Status', type: 'select', options: giftcardStatusOptions },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT_STATUS', labelFallback: 'Payment status', type: 'select', options: paymentStatusOptions },
      ...orderDateSearchFields,
    ],
    columns: [
      { key: 'order_id_formatted', labelKey: 'LBL_Order_ID', labelFallback: 'Order ID' },
      { key: 'user_full_name', labelKey: 'LBL_user_name', labelFallback: 'User name' },
      { key: 'order_total_amount', labelKey: 'LBL_Total', labelFallback: 'Total' },
      { key: 'ordgift_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  wallet: {
    module: 'wallet',
    pageLangKey: 'wallet',
    titleKey: 'LBL_WALLET_RECHARGE_ORDERS',
    titleFallback: 'Wallet Recharge Orders',
    useConfigTitle: true,
    exportable: true,
    tableClassName: 'table--hovered',
    searchDateInputClass: 'small dateTimeFld field--calender',
    hidePageWarning: true,
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT_STATUS', labelFallback: 'Payment status', type: 'select', options: paymentStatusOptions },
      ...orderDateSearchFields,
    ],
    columns: [
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'user_full_name', labelKey: 'LBL_USER_NAME', labelFallback: 'User name' },
      { key: 'order_total_amount', labelKey: 'LBL_TOTAL', labelFallback: 'Total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
  'order-subscription-plans': {
    module: 'order-subscription-plans',
    pageLangKey: 'order-subscription-plans',
    titleKey: 'LBL_SUBSCRIPTION_PLAN_ORDERS',
    titleFallback: 'Subscription Plan Orders',
    exportable: true,
    tableClassName: 'table--hovered',
    searchFields: [
      { name: 'keyword', labelKey: 'LBL_KEYWORD', labelFallback: 'Keyword', type: 'text' },
      { name: 'order_payment_status', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment', type: 'select', options: paymentStatusOptions },
    ],
    columns: [
      { key: 'ordsplan_id', labelKey: 'LBL_SUBSCRIPTION_ID', labelFallback: 'Subscription ID' },
      { key: 'order_id_formatted', labelKey: 'LBL_ORDER_ID', labelFallback: 'Order ID' },
      { key: 'plan_name', labelKey: 'LBL_PLAN_NAME', labelFallback: 'Plan name' },
      { key: 'ordsplan_start_date', labelKey: 'LBL_START_DATE', labelFallback: 'Start date' },
      { key: 'ordsplan_end_date', labelKey: 'LBL_END_DATE', labelFallback: 'End date' },
      { key: 'learner_name', labelKey: 'LBL_LEARNER', labelFallback: 'Learner' },
      { key: 'order_net_amount', labelKey: 'LBL_NET_TOTAL', labelFallback: 'Net total' },
      { key: 'order_payment_status_label', labelKey: 'LBL_PAYMENT', labelFallback: 'Payment' },
      { key: 'order_addedon', labelKey: 'LBL_DATETIME', labelFallback: 'Datetime' },
      { key: 'ordsplan_status_label', labelKey: 'LBL_STATUS', labelFallback: 'Status' },
      { key: 'action', labelKey: 'LBL_ACTION', labelFallback: 'Action', align: 'right' },
    ],
  },
};
